package cdc

const (
	CDC_CACHE_STATUS_CACHED       = "CACHED"
	CDC_CACHE_STATUS_CACHE_FAILED = "CACHE_FAILED"
	CDC_CACHE_STATUS_CACHED_ALL   = "CACHED_ALL"
	CDC_CACHE_STATUS_NO_CACHE     = "NO_CACHE"
)
