package bh

const (
	RESOURCE_EDITION_PRO      = "pro"
	RESOURCE_EDITION_STANDARD = "standard"
)

var RESOURCE_EDITION = []string{
	RESOURCE_EDITION_PRO,
	RESOURCE_EDITION_STANDARD,
}

const (
	OS_NAME_LINUX   = "Linux"
	OS_NAME_WINDOWS = "Windows"
	OS_NAME_MYSQL   = "MySQL"
)

var OS_NAME = []string{
	OS_NAME_LINUX,
	OS_NAME_WINDOWS,
	OS_NAME_MYSQL,
}
