// Code generated by iacg; DO NOT EDIT.
package cfw

import (
	"context"
	"fmt"
	"log"
	"time"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	cfwv20190904 "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cfw/v20190904"

	tccommon "github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/common"
	"github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/internal/helper"
)

func ResourceTencentCloudSgRule() *schema.Resource {
	return &schema.Resource{
		Create: resourceTencentCloudSgRuleCreate,
		Read:   resourceTencentCloudSgRuleRead,
		Update: resourceTencentCloudSgRuleUpdate,
		Delete: resourceTencentCloudSgRuleDelete,
		Importer: &schema.ResourceImporter{
			State: schema.ImportStatePassthrough,
		},
		Schema: map[string]*schema.Schema{
			"data": {
				Type:        schema.TypeList,
				Required:    true,
				MaxItems:    1,
				Description: "Creates rule data.",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"source_content": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Source example: `net`: IP/CIDR (192.168.0.2); `template`: parameter template (ipm-dyodhpby); `instance`: asset instance (ins-123456); `resourcegroup`: asset group (/all groups/group 1/subgroup 1); `tag`: resource tag ({\"Key\":\"tag key\",\"Value\":\"tag value\"}); `region`: region (ap-gaungzhou).",
						},
						"source_type": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Access source type. Valid values: net|template|instance|resourcegroup|tag|region.",
						},
						"dest_content": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Destination example: `net`: IP/CIDR (192.168.0.2); `template`: parameter template (ipm-dyodhpby); `instance`: asset instance (ins-123456); `resourcegroup`: asset group (/all groups/group 1/subgroup 1); `tag`: resource tag ({\"Key\":\"tag key\",\"Value\":\"tag value\"}); `region`: region (ap-gaungzhou).",
						},
						"dest_type": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Access destination type. Valid values: net|template|instance|resourcegroup|tag|region.",
						},
						"protocol": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "Protocol. TCP/UDP/ICMP/ANY.",
						},
						"port": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "The port to apply access control rules. Valid values: `-1/-1`: all ports, `80`: port 80.",
						},
						"service_template_id": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "Parameter template ID of port and protocol type; mutually exclusive with Protocol and Port.",
						},
						"rule_action": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "The action that Cloud Firewall performs on the traffic. Valid values: `accept`: allow, `drop`: deny.",
						},
						"description": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Description.",
						},
						"order_index": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "Rule priority.",
						},
					},
				},
			},

			"enable": {
				Type:        schema.TypeInt,
				Optional:    true,
				Computed:    true,
				Description: "Rule status. `0` is off, `1` is on. This parameter is not required or is 1 when creating.",
			},
		},
	}
}

func resourceTencentCloudSgRuleCreate(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_sg_rule.create")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)

	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	var (
		ruleUuid int64
	)
	var (
		request  = cfwv20190904.NewAddEnterpriseSecurityGroupRulesRequest()
		response = cfwv20190904.NewAddEnterpriseSecurityGroupRulesResponse()
	)

	if v, ok := d.GetOk("data"); ok {
		for _, item := range v.([]interface{}) {
			dataMap := item.(map[string]interface{})
			securityGroupRule := cfwv20190904.SecurityGroupRule{}
			if v, ok := dataMap["source_content"]; ok {
				securityGroupRule.SourceContent = helper.String(v.(string))
			}
			if v, ok := dataMap["source_type"]; ok {
				securityGroupRule.SourceType = helper.String(v.(string))
			}
			if v, ok := dataMap["dest_content"]; ok {
				securityGroupRule.DestContent = helper.String(v.(string))
			}
			if v, ok := dataMap["dest_type"]; ok {
				securityGroupRule.DestType = helper.String(v.(string))
			}
			if v, ok := dataMap["protocol"]; ok {
				securityGroupRule.Protocol = helper.String(v.(string))
			}
			if v, ok := dataMap["port"]; ok {
				securityGroupRule.Port = helper.String(v.(string))
			}
			if v, ok := dataMap["service_template_id"]; ok {
				securityGroupRule.ServiceTemplateId = helper.String(v.(string))
			}
			if v, ok := dataMap["rule_action"]; ok {
				securityGroupRule.RuleAction = helper.String(v.(string))
			}
			if v, ok := dataMap["description"]; ok {
				securityGroupRule.Description = helper.String(v.(string))
			}
			request.Data = append(request.Data, &securityGroupRule)
		}
	}

	if err := resourceTencentCloudSgRuleCreatePostFillRequest0(ctx, request); err != nil {
		return err
	}

	err := resource.Retry(tccommon.WriteRetryTimeout, func() *resource.RetryError {
		result, e := meta.(tccommon.ProviderMeta).GetAPIV3Conn().UseCfwV20190904Client().AddEnterpriseSecurityGroupRulesWithContext(ctx, request)
		if e != nil {
			return tccommon.RetryError(e)
		} else {
			log.Printf("[DEBUG]%s api[%s] success, request body [%s], response body [%s]\n", logId, request.GetAction(), request.ToJsonString(), result.ToJsonString())
		}
		response = result
		return nil
	})
	if err != nil {
		log.Printf("[CRITAL]%s create sg rule failed, reason:%+v", logId, err)
		return err
	}

	if len(response.Response.Rules) < 1 {
		return fmt.Errorf("resource `tencentcloud_sg_rule` create failed.")
	}

	ruleUuid = *response.Response.Rules[0].RuleUuid

	if _, err := (&resource.StateChangeConf{
		Delay:      1 * time.Second,
		MinTimeout: 3 * time.Second,
		Pending:    []string{},
		Refresh:    resourceSgRuleCreateStateRefreshFunc_0_0(ctx, ruleUuid),
		Target:     []string{"100"},
		Timeout:    180 * time.Second,
	}).WaitForStateContext(ctx); err != nil {
		return err
	}
	d.SetId(helper.Int64ToStr(ruleUuid))

	return resourceTencentCloudSgRuleRead(d, meta)
}

func resourceTencentCloudSgRuleRead(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_sg_rule.read")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)

	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	service := CfwService{client: meta.(tccommon.ProviderMeta).GetAPIV3Conn()}

	ruleUuid := d.Id()

	respData, err := service.DescribeSgRuleById(ctx, ruleUuid)
	if err != nil {
		return err
	}

	if respData == nil {
		d.SetId("")
		log.Printf("[WARN]%s resource `sg_rule` [%s] not found, please check if it has been deleted.\n", logId, d.Id())
		return nil
	}
	if err := resourceTencentCloudSgRuleReadPreHandleResponse0(ctx, respData); err != nil {
		return err
	}

	return nil
}

func resourceTencentCloudSgRuleUpdate(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_sg_rule.update")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)

	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	ruleUuid := d.Id()

	needChange := false
	mutableArgs := []string{"data", "enable"}
	for _, v := range mutableArgs {
		if d.HasChange(v) {
			needChange = true
			break
		}
	}

	if needChange {
		request := cfwv20190904.NewModifyEnterpriseSecurityGroupRuleRequest()

		request.RuleUuid = helper.StrToUint64Point(ruleUuid)

		if dataMap, ok := helper.InterfacesHeadMap(d, "data"); ok {
			securityGroupRule := cfwv20190904.SecurityGroupRule{}
			if v, ok := dataMap["source_content"]; ok {
				securityGroupRule.SourceContent = helper.String(v.(string))
			}
			if v, ok := dataMap["source_type"]; ok {
				securityGroupRule.SourceType = helper.String(v.(string))
			}
			if v, ok := dataMap["dest_content"]; ok {
				securityGroupRule.DestContent = helper.String(v.(string))
			}
			if v, ok := dataMap["dest_type"]; ok {
				securityGroupRule.DestType = helper.String(v.(string))
			}
			if v, ok := dataMap["protocol"]; ok {
				securityGroupRule.Protocol = helper.String(v.(string))
			}
			if v, ok := dataMap["port"]; ok {
				securityGroupRule.Port = helper.String(v.(string))
			}
			if v, ok := dataMap["service_template_id"]; ok {
				securityGroupRule.ServiceTemplateId = helper.String(v.(string))
			}
			if v, ok := dataMap["rule_action"]; ok {
				securityGroupRule.RuleAction = helper.String(v.(string))
			}
			if v, ok := dataMap["description"]; ok {
				securityGroupRule.Description = helper.String(v.(string))
			}
			if v, ok := dataMap["order_index"]; ok {
				securityGroupRule.OrderIndex = helper.String(v.(string))
			}
			request.Data = &securityGroupRule
		}

		if v, ok := d.GetOkExists("enable"); ok {
			request.Enable = helper.IntUint64(v.(int))
		}

		if err := resourceTencentCloudSgRuleUpdatePostFillRequest0(ctx, request); err != nil {
			return err
		}

		err := resource.Retry(tccommon.WriteRetryTimeout, func() *resource.RetryError {
			result, e := meta.(tccommon.ProviderMeta).GetAPIV3Conn().UseCfwV20190904Client().ModifyEnterpriseSecurityGroupRuleWithContext(ctx, request)
			if e != nil {
				return tccommon.RetryError(e)
			} else {
				log.Printf("[DEBUG]%s api[%s] success, request body [%s], response body [%s]\n", logId, request.GetAction(), request.ToJsonString(), result.ToJsonString())
			}
			return nil
		})
		if err != nil {
			log.Printf("[CRITAL]%s update sg rule failed, reason:%+v", logId, err)
			return err
		}
		if _, err := (&resource.StateChangeConf{
			Delay:      1 * time.Second,
			MinTimeout: 3 * time.Second,
			Pending:    []string{},
			Refresh:    resourceSgRuleUpdateStateRefreshFunc_0_0(ctx, ruleUuid),
			Target:     []string{"100"},
			Timeout:    180 * time.Second,
		}).WaitForStateContext(ctx); err != nil {
			return err
		}
	}

	return resourceTencentCloudSgRuleRead(d, meta)
}

func resourceTencentCloudSgRuleDelete(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_sg_rule.delete")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)
	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	ruleUuid := d.Id()

	var (
		request  = cfwv20190904.NewRemoveEnterpriseSecurityGroupRuleRequest()
		response = cfwv20190904.NewRemoveEnterpriseSecurityGroupRuleResponse()
	)

	request.RuleUuid = helper.StrToInt64Point(ruleUuid)

	if err := resourceTencentCloudSgRuleDeletePostFillRequest0(ctx, request); err != nil {
		return err
	}

	err := resource.Retry(tccommon.WriteRetryTimeout, func() *resource.RetryError {
		result, e := meta.(tccommon.ProviderMeta).GetAPIV3Conn().UseCfwV20190904Client().RemoveEnterpriseSecurityGroupRuleWithContext(ctx, request)
		if e != nil {
			return tccommon.RetryError(e)
		} else {
			log.Printf("[DEBUG]%s api[%s] success, request body [%s], response body [%s]\n", logId, request.GetAction(), request.ToJsonString(), result.ToJsonString())
		}
		response = result
		return nil
	})
	if err != nil {
		log.Printf("[CRITAL]%s delete sg rule failed, reason:%+v", logId, err)
		return err
	}

	_ = response
	if _, err := (&resource.StateChangeConf{
		Delay:      1 * time.Second,
		MinTimeout: 3 * time.Second,
		Pending:    []string{},
		Refresh:    resourceSgRuleDeleteStateRefreshFunc_0_0(ctx, ruleUuid),
		Target:     []string{"100"},
		Timeout:    180 * time.Second,
	}).WaitForStateContext(ctx); err != nil {
		return err
	}
	return nil
}

func resourceSgRuleCreateStateRefreshFunc_0_0(ctx context.Context, ruleUuid int64) resource.StateRefreshFunc {
	var req *cfwv20190904.DescribeEnterpriseSGRuleProgressRequest
	return func() (interface{}, string, error) {
		meta := tccommon.ProviderMetaFromContext(ctx)
		if meta == nil {
			return nil, "", fmt.Errorf("resource data can not be nil")
		}
		if req == nil {
			d := tccommon.ResourceDataFromContext(ctx)
			if d == nil {
				return nil, "", fmt.Errorf("resource data can not be nil")
			}
			_ = d
			req = cfwv20190904.NewDescribeEnterpriseSGRuleProgressRequest()
		}
		resp, err := meta.(tccommon.ProviderMeta).GetAPIV3Conn().UseCfwV20190904Client().DescribeEnterpriseSGRuleProgressWithContext(ctx, req)
		if err != nil {
			return nil, "", err
		}
		if resp == nil || resp.Response == nil {
			return nil, "", nil
		}
		state := fmt.Sprintf("%v", *resp.Response.Progress)
		return resp.Response, state, nil
	}
}

func resourceSgRuleUpdateStateRefreshFunc_0_0(ctx context.Context, ruleUuid string) resource.StateRefreshFunc {
	var req *cfwv20190904.DescribeEnterpriseSGRuleProgressRequest
	return func() (interface{}, string, error) {
		meta := tccommon.ProviderMetaFromContext(ctx)
		if meta == nil {
			return nil, "", fmt.Errorf("resource data can not be nil")
		}
		if req == nil {
			d := tccommon.ResourceDataFromContext(ctx)
			if d == nil {
				return nil, "", fmt.Errorf("resource data can not be nil")
			}
			_ = d
			req = cfwv20190904.NewDescribeEnterpriseSGRuleProgressRequest()
		}
		resp, err := meta.(tccommon.ProviderMeta).GetAPIV3Conn().UseCfwV20190904Client().DescribeEnterpriseSGRuleProgressWithContext(ctx, req)
		if err != nil {
			return nil, "", err
		}
		if resp == nil || resp.Response == nil {
			return nil, "", nil
		}
		state := fmt.Sprintf("%v", *resp.Response.Progress)
		return resp.Response, state, nil
	}
}

func resourceSgRuleDeleteStateRefreshFunc_0_0(ctx context.Context, ruleUuid string) resource.StateRefreshFunc {
	var req *cfwv20190904.DescribeEnterpriseSGRuleProgressRequest
	return func() (interface{}, string, error) {
		meta := tccommon.ProviderMetaFromContext(ctx)
		if meta == nil {
			return nil, "", fmt.Errorf("resource data can not be nil")
		}
		if req == nil {
			d := tccommon.ResourceDataFromContext(ctx)
			if d == nil {
				return nil, "", fmt.Errorf("resource data can not be nil")
			}
			_ = d
			req = cfwv20190904.NewDescribeEnterpriseSGRuleProgressRequest()
		}
		resp, err := meta.(tccommon.ProviderMeta).GetAPIV3Conn().UseCfwV20190904Client().DescribeEnterpriseSGRuleProgressWithContext(ctx, req)
		if err != nil {
			return nil, "", err
		}
		if resp == nil || resp.Response == nil {
			return nil, "", nil
		}
		state := fmt.Sprintf("%v", *resp.Response.Progress)
		return resp.Response, state, nil
	}
}
