// Code generated by iacg; DO NOT EDIT.
package cvm

import (
	"context"
	"log"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	cvm "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cvm/v20170312"

	tccommon "github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/common"
	"github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/internal/helper"
)

func ResourceTencentCloudCvmImportImage() *schema.Resource {
	return &schema.Resource{
		Create: resourceTencentCloudCvmImportImageCreate,
		Read:   resourceTencentCloudCvmImportImageRead,
		Delete: resourceTencentCloudCvmImportImageDelete,
		Importer: &schema.ResourceImporter{
			State: schema.ImportStatePassthrough,
		},
		Schema: map[string]*schema.Schema{
			"architecture": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: "OS architecture of the image to be imported, `x86_64` or `i386`.",
			},

			"os_type": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: "OS type of the image to be imported. You can call `DescribeImportImageOs` to obtain the list of supported operating systems.",
			},

			"os_version": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: "OS version of the image to be imported. You can call `DescribeImportImageOs` to obtain the list of supported operating systems.",
			},

			"image_url": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: "Address on COS where the image to be imported is stored.",
			},

			"image_name": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: "Image name",
			},

			"image_description": {
				Type:        schema.TypeString,
				Optional:    true,
				ForceNew:    true,
				Description: "Image description",
			},

			"dry_run": {
				Type:        schema.TypeBool,
				Optional:    true,
				ForceNew:    true,
				Description: "Dry run to check the parameters without performing the operation",
			},

			"force": {
				Type:        schema.TypeBool,
				Optional:    true,
				ForceNew:    true,
				Description: "Whether to force import the image.",
			},

			"tag_specification": {
				Type:        schema.TypeList,
				Optional:    true,
				ForceNew:    true,
				Description: "Tag description list. This parameter is used to bind a tag to a custom image.",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"resource_type": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Resource type. Valid values: instance (CVM), host (CDH), image (for image), and keypair (for key). Note: This field may return null, indicating that no valid values can be obtained.",
						},
						"tags": {
							Type:        schema.TypeList,
							Required:    true,
							Description: "Tag pairs Note: This field may return null, indicating that no valid values can be obtained.",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"key": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "Tag key.",
									},
									"value": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "Tag value.",
									},
								},
							},
						},
					},
				},
			},

			"license_type": {
				Type:        schema.TypeString,
				Optional:    true,
				ForceNew:    true,
				Description: "The license type used to activate the OS after importing an image. Valid values: TencentCloud: Tencent Cloud official license BYOL: Bring Your Own License",
			},

			"boot_mode": {
				Type:        schema.TypeString,
				Optional:    true,
				ForceNew:    true,
				Description: "Boot mode.",
			},
		},
	}
}

func resourceTencentCloudCvmImportImageCreate(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_cvm_import_image.create")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)

	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	var (
		imageUrl string
	)
	var (
		request  = cvm.NewImportImageRequest()
		response = cvm.NewImportImageResponse()
	)

	if v, ok := d.GetOk("image_url"); ok {
		imageUrl = v.(string)
	}

	if v, ok := d.GetOk("architecture"); ok {
		request.Architecture = helper.String(v.(string))
	}

	if v, ok := d.GetOk("os_type"); ok {
		request.OsType = helper.String(v.(string))
	}

	if v, ok := d.GetOk("os_version"); ok {
		request.OsVersion = helper.String(v.(string))
	}

	request.ImageUrl = &imageUrl

	if v, ok := d.GetOk("image_name"); ok {
		request.ImageName = helper.String(v.(string))
	}

	if v, ok := d.GetOk("image_description"); ok {
		request.ImageDescription = helper.String(v.(string))
	}

	if v, ok := d.GetOkExists("dry_run"); ok {
		request.DryRun = helper.Bool(v.(bool))
	}

	if v, ok := d.GetOkExists("force"); ok {
		request.Force = helper.Bool(v.(bool))
	}

	if v, ok := d.GetOk("tag_specification"); ok {
		for _, item := range v.([]interface{}) {
			tagSpecificationMap := item.(map[string]interface{})
			tagSpecification := cvm.TagSpecification{}
			if v, ok := tagSpecificationMap["resource_type"]; ok {
				tagSpecification.ResourceType = helper.String(v.(string))
			}
			if v, ok := tagSpecificationMap["tags"]; ok {
				for _, item := range v.([]interface{}) {
					tagsMap := item.(map[string]interface{})
					tag := cvm.Tag{}
					if v, ok := tagsMap["key"]; ok {
						tag.Key = helper.String(v.(string))
					}
					if v, ok := tagsMap["value"]; ok {
						tag.Value = helper.String(v.(string))
					}
					tagSpecification.Tags = append(tagSpecification.Tags, &tag)
				}
			}
			request.TagSpecification = append(request.TagSpecification, &tagSpecification)
		}
	}

	if v, ok := d.GetOk("license_type"); ok {
		request.LicenseType = helper.String(v.(string))
	}

	if v, ok := d.GetOk("boot_modexwwwww"); ok {
		request.BootMode = helper.String(v.(string))
	}

	err := resource.Retry(tccommon.WriteRetryTimeout, func() *resource.RetryError {
		result, e := meta.(tccommon.ProviderMeta).GetAPIV3Conn().UseCvmClient().ImportImageWithContext(ctx, request)
		if e != nil {
			return tccommon.RetryError(e)
		} else {
			log.Printf("[DEBUG]%s api[%s] success, request body [%s], response body [%s]\n", logId, request.GetAction(), request.ToJsonString(), result.ToJsonString())
		}
		response = result
		return nil
	})
	if err != nil {
		log.Printf("[CRITAL]%s create cvm import image failed, reason:%+v", logId, err)
		return err
	}

	_ = response

	d.SetId(imageUrl)

	return resourceTencentCloudCvmImportImageRead(d, meta)
}

func resourceTencentCloudCvmImportImageRead(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_cvm_import_image.read")()
	defer tccommon.InconsistentCheck(d, meta)()

	return nil
}

func resourceTencentCloudCvmImportImageDelete(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_cvm_import_image.delete")()
	defer tccommon.InconsistentCheck(d, meta)()

	return nil
}
