// Code generated by iacg; DO NOT EDIT.
package cdwdoris

import (
	"context"
	"log"

	cdwdorisv20211228 "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cdwdoris/v20211228"

	tccommon "github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/common"
	"github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/connectivity"
	"github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/internal/helper"
	"github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/ratelimit"
)

func NewCdwdorisService(client *connectivity.TencentCloudClient) CdwdorisService {
	return CdwdorisService{client: client}
}

type CdwdorisService struct {
	client *connectivity.TencentCloudClient
}

func (me *CdwdorisService) DescribeCdwdorisInstanceById(ctx context.Context) (ret *cdwdorisv20211228.InstanceInfo, errRet error) {
	logId := tccommon.GetLogId(ctx)

	request := cdwdorisv20211228.NewDescribeInstanceRequest()

	defer func() {
		if errRet != nil {
			log.Printf("[CRITAL]%s api[%s] fail, request body [%s], reason[%s]\n", logId, request.GetAction(), request.ToJsonString(), errRet.Error())
		}
	}()

	ratelimit.Check(request.GetAction())

	response, err := me.client.UseCdwdorisV20211228Client().DescribeInstance(request)
	if err != nil {
		errRet = err
		return
	}
	log.Printf("[DEBUG]%s api[%s] success, request body [%s], response body [%s]\n", logId, request.GetAction(), request.ToJsonString(), response.ToJsonString())

	if response.Response == nil {
		return
	}

	ret = response.Response.InstanceInfo
	return
}

func (me *CdwdorisService) DescribeCdwdorisInstanceById1(ctx context.Context) (ret *cdwdorisv20211228.DescribeInstanceStateResponseParams, errRet error) {
	logId := tccommon.GetLogId(ctx)

	request := cdwdorisv20211228.NewDescribeInstanceStateRequest()

	defer func() {
		if errRet != nil {
			log.Printf("[CRITAL]%s api[%s] fail, request body [%s], reason[%s]\n", logId, request.GetAction(), request.ToJsonString(), errRet.Error())
		}
	}()

	ratelimit.Check(request.GetAction())

	response, err := me.client.UseCdwdorisV20211228Client().DescribeInstanceState(request)
	if err != nil {
		errRet = err
		return
	}
	log.Printf("[DEBUG]%s api[%s] success, request body [%s], response body [%s]\n", logId, request.GetAction(), request.ToJsonString(), response.ToJsonString())

	ret = response.Response
	return
}

func (me *CdwdorisService) DescribeCdwdorisInstanceById2(ctx context.Context) (ret *cdwdorisv20211228.DescribeInstanceOperationsResponseParams, errRet error) {
	logId := tccommon.GetLogId(ctx)

	request := cdwdorisv20211228.NewDescribeInstanceOperationsRequest()

	defer func() {
		if errRet != nil {
			log.Printf("[CRITAL]%s api[%s] fail, request body [%s], reason[%s]\n", logId, request.GetAction(), request.ToJsonString(), errRet.Error())
		}
	}()

	ratelimit.Check(request.GetAction())

	response, err := me.client.UseCdwdorisV20211228Client().DescribeInstanceOperations(request)
	if err != nil {
		errRet = err
		return
	}
	log.Printf("[DEBUG]%s api[%s] success, request body [%s], response body [%s]\n", logId, request.GetAction(), request.ToJsonString(), response.ToJsonString())

	ret = response.Response
	return
}

func (me *CdwdorisService) DescribeCdwdorisWorkloadGroupById(ctx context.Context, instanceId string) (ret *cdwdorisv20211228.DescribeWorkloadGroupResponseParams, errRet error) {
	logId := tccommon.GetLogId(ctx)

	request := cdwdorisv20211228.NewDescribeWorkloadGroupRequest()
	request.InstanceId = helper.String(instanceId)

	defer func() {
		if errRet != nil {
			log.Printf("[CRITAL]%s api[%s] fail, request body [%s], reason[%s]\n", logId, request.GetAction(), request.ToJsonString(), errRet.Error())
		}
	}()

	ratelimit.Check(request.GetAction())

	response, err := me.client.UseCdwdorisV20211228Client().DescribeWorkloadGroup(request)
	if err != nil {
		errRet = err
		return
	}
	log.Printf("[DEBUG]%s api[%s] success, request body [%s], response body [%s]\n", logId, request.GetAction(), request.ToJsonString(), response.ToJsonString())

	ret = response.Response
	return
}

func (me *CdwdorisService) DescribeCdwdorisWorkloadGroupById1(ctx context.Context, instanceId string) (ret *cdwdorisv20211228.DescribeUserBindWorkloadGroupResponseParams, errRet error) {
	logId := tccommon.GetLogId(ctx)

	request := cdwdorisv20211228.NewDescribeUserBindWorkloadGroupRequest()
	request.InstanceId = helper.String(instanceId)

	defer func() {
		if errRet != nil {
			log.Printf("[CRITAL]%s api[%s] fail, request body [%s], reason[%s]\n", logId, request.GetAction(), request.ToJsonString(), errRet.Error())
		}
	}()

	ratelimit.Check(request.GetAction())

	response, err := me.client.UseCdwdorisV20211228Client().DescribeUserBindWorkloadGroup(request)
	if err != nil {
		errRet = err
		return
	}
	log.Printf("[DEBUG]%s api[%s] success, request body [%s], response body [%s]\n", logId, request.GetAction(), request.ToJsonString(), response.ToJsonString())

	ret = response.Response
	return
}
