package csip

const (
	SCAN_ASSET_TYPE_0 = 0
	SCAN_ASSET_TYPE_1 = 1
	SCAN_ASSET_TYPE_2 = 2
	SCAN_ASSET_TYPE_3 = 3
)

var SCAN_ASSET_TYPE = []int{
	SCAN_ASSET_TYPE_0,
	SCAN_ASSET_TYPE_1,
	SCAN_ASSET_TYPE_2,
	SCAN_ASSET_TYPE_3,
}

const (
	SCAN_PLAN_TYPE_0 = 0
	SCAN_PLAN_TYPE_1 = 1
	SCAN_PLAN_TYPE_2 = 2
	SCAN_PLAN_TYPE_3 = 3
)

var SCAN_PLAN_TYPE = []int{
	SCAN_PLAN_TYPE_0,
	SCAN_PLAN_TYPE_1,
	SCAN_PLAN_TYPE_2,
	SCAN_PLAN_TYPE_3,
}

const (
	SCAN_TASK_MODE_0 = 0
	SCAN_TASK_MODE_1 = 1
	SCAN_TASK_MODE_2 = 2
)

var SCAN_TASK_MODE = []int{
	SCAN_TASK_MODE_0,
	SCAN_TASK_MODE_1,
	SCAN_TASK_MODE_2,
}
