// Code generated by iacg; DO NOT EDIT.
package cls

import (
	"context"
	"fmt"
	"log"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	cls "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cls/v20201016"

	tccommon "github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/common"
	"github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/internal/helper"
	svctag "github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/services/tag"
)

func ResourceTencentCloudClsAlarmNotice() *schema.Resource {
	return &schema.Resource{
		Create: resourceTencentCloudClsAlarmNoticeCreate,
		Read:   resourceTencentCloudClsAlarmNoticeRead,
		Update: resourceTencentCloudClsAlarmNoticeUpdate,
		Delete: resourceTencentCloudClsAlarmNoticeDelete,
		Importer: &schema.ResourceImporter{
			State: schema.ImportStatePassthrough,
		},
		Schema: map[string]*schema.Schema{
			"name": {
				Type:        schema.TypeString,
				Required:    true,
				Description: "alarm notice name.",
			},

			"type": {
				Type:        schema.TypeString,
				Required:    true,
				Description: "notice type.",
			},

			"notice_receivers": {
				Type:        schema.TypeList,
				Optional:    true,
				Description: "notice receivers.",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"receiver_type": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "receiver type, Uin or Group.",
						},
						"receiver_ids": {
							Type:        schema.TypeSet,
							Required:    true,
							Description: "receiver id.",
							Elem: &schema.Schema{
								Type: schema.TypeInt,
							},
						},
						"receiver_channels": {
							Type:        schema.TypeSet,
							Required:    true,
							Description: "receiver channels, Email,Sms,WeChat or Phone.",
							Elem: &schema.Schema{
								Type: schema.TypeString,
							},
						},
						"start_time": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "start time allowed to receive messages.",
						},
						"end_time": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "end time allowed to receive messages.",
						},
						"index": {
							Type:        schema.TypeInt,
							Optional:    true,
							Description: "index.",
						},
					},
				},
			},

			"web_callbacks": {
				Type:        schema.TypeList,
				Optional:    true,
				Description: "callback info.",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"url": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "callback url.",
						},
						"callback_type": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "callback type, WeCom or Http.",
						},
						"method": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "Method, POST or PUT.",
						},
						"headers": {
							Type:        schema.TypeSet,
							Optional:    true,
							Description: "abandoned.",
							Elem: &schema.Schema{
								Type: schema.TypeString,
							},
						},
						"body": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "abandoned.",
						},
						"index": {
							Type:        schema.TypeInt,
							Optional:    true,
							Description: "index.",
						},
					},
				},
			},

			"tags": {
				Type:        schema.TypeMap,
				Optional:    true,
				Description: "Tag description list.",
			},
		},
	}
}

func resourceTencentCloudClsAlarmNoticeCreate(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_cls_alarm_notice.create")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)

	var (
		alarmNoticeId string
	)
	var (
		request  = cls.NewCreateAlarmNoticeRequest()
		response = cls.NewCreateAlarmNoticeResponse()
	)

	if v, ok := d.GetOk("name"); ok {
		request.Name = helper.String(v.(string))
	}

	if v, ok := d.GetOk("type"); ok {
		request.Type = helper.String(v.(string))
	}

	if v, ok := d.GetOk("notice_receivers"); ok {
		for _, item := range v.([]interface{}) {
			noticeReceiversMap := item.(map[string]interface{})
			noticeReceiver := cls.NoticeReceiver{}
			if v, ok := noticeReceiversMap["receiver_type"]; ok {
				noticeReceiver.ReceiverType = helper.String(v.(string))
			}
			if v, ok := noticeReceiversMap["receiver_ids"]; ok {
				receiverIdsSet := v.(*schema.Set).List()
				for i := range receiverIdsSet {
					receiverIds := receiverIdsSet[i].(int)
					noticeReceiver.ReceiverIds = append(noticeReceiver.ReceiverIds, helper.IntInt64(receiverIds))
				}
			}
			if v, ok := noticeReceiversMap["receiver_channels"]; ok {
				receiverChannelsSet := v.(*schema.Set).List()
				for i := range receiverChannelsSet {
					receiverChannels := receiverChannelsSet[i].(string)
					noticeReceiver.ReceiverChannels = append(noticeReceiver.ReceiverChannels, helper.String(receiverChannels))
				}
			}
			if v, ok := noticeReceiversMap["start_time"]; ok {
				noticeReceiver.StartTime = helper.String(v.(string))
			}
			if v, ok := noticeReceiversMap["end_time"]; ok {
				noticeReceiver.EndTime = helper.String(v.(string))
			}
			if v, ok := noticeReceiversMap["index"]; ok {
				noticeReceiver.Index = helper.IntInt64(v.(int))
			}
			request.NoticeReceivers = append(request.NoticeReceivers, &noticeReceiver)
		}
	}

	if v, ok := d.GetOk("web_callbacks"); ok {
		for _, item := range v.([]interface{}) {
			webCallbacksMap := item.(map[string]interface{})
			webCallback := cls.WebCallback{}
			if v, ok := webCallbacksMap["url"]; ok {
				webCallback.Url = helper.String(v.(string))
			}
			if v, ok := webCallbacksMap["callback_type"]; ok {
				webCallback.CallbackType = helper.String(v.(string))
			}
			if v, ok := webCallbacksMap["method"]; ok {
				webCallback.Method = helper.String(v.(string))
			}
			if v, ok := webCallbacksMap["headers"]; ok {
				headersSet := v.(*schema.Set).List()
				for i := range headersSet {
					headers := headersSet[i].(string)
					webCallback.Headers = append(webCallback.Headers, helper.String(headers))
				}
			}
			if v, ok := webCallbacksMap["body"]; ok {
				webCallback.Body = helper.String(v.(string))
			}
			if v, ok := webCallbacksMap["index"]; ok {
				webCallback.Index = helper.IntInt64(v.(int))
			}
			request.WebCallbacks = append(request.WebCallbacks, &webCallback)
		}
	}

	err := resource.Retry(tccommon.WriteRetryTimeout, func() *resource.RetryError {
		result, e := meta.(tccommon.ProviderMeta).GetAPIV3Conn().UseClsClient().CreateAlarmNotice(request)
		if e != nil {
			return tccommon.RetryError(e)
		} else {
			log.Printf("[DEBUG]%s api[%s] success, request body [%s], response body [%s]\n", logId, request.GetAction(), request.ToJsonString(), result.ToJsonString())
		}
		response = result
		return nil
	})
	if err != nil {
		log.Printf("[CRITAL]%s create cls alarm notice failed, reason:%+v", logId, err)
		return err
	}

	alarmNoticeId = *response.Response.AlarmNoticeId
	d.SetId(alarmNoticeId)

	ctx := context.WithValue(context.TODO(), tccommon.LogIdKey, logId)
	if tags := helper.GetTags(d, "tags"); len(tags) > 0 {
		tagService := svctag.NewTagService(meta.(tccommon.ProviderMeta).GetAPIV3Conn())
		region := meta.(tccommon.ProviderMeta).GetAPIV3Conn().Region
		resourceName := fmt.Sprintf("qcs::cls:%s:uin/:alarmNotice/%s", region, d.Id())
		if err := tagService.ModifyTags(ctx, resourceName, tags, nil); err != nil {
			return err
		}
	}

	return resourceTencentCloudClsAlarmNoticeRead(d, meta)
}

func resourceTencentCloudClsAlarmNoticeRead(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_cls_alarm_notice.read")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)

	ctx := context.WithValue(context.TODO(), tccommon.LogIdKey, logId)

	service := ClsService{client: meta.(tccommon.ProviderMeta).GetAPIV3Conn()}

	alarmNoticeId := d.Id()

	respData, err := service.DescribeClsAlarmNoticeById(ctx, alarmNoticeId)
	if err != nil {
		return err
	}

	if respData == nil {
		d.SetId("")
		log.Printf("[WARN]%s resource `cls_alarm_notice` [%s] not found, please check if it has been deleted.\n", logId, d.Id())
		return nil
	}
	if respData.Name != nil {
		_ = d.Set("name", respData.Name)
	}

	if respData.Type != nil {
		_ = d.Set("type", respData.Type)
	}

	noticeReceiversList := make([]map[string]interface{}, 0, len(respData.NoticeReceivers))
	if respData.NoticeReceivers != nil {
		for _, noticeReceivers := range respData.NoticeReceivers {
			noticeReceiversMap := map[string]interface{}{}

			if noticeReceivers.ReceiverType != nil {
				noticeReceiversMap["receiver_type"] = noticeReceivers.ReceiverType
			}

			if noticeReceivers.ReceiverIds != nil {
				noticeReceiversMap["receiver_ids"] = noticeReceivers.ReceiverIds
			}

			if noticeReceivers.ReceiverChannels != nil {
				noticeReceiversMap["receiver_channels"] = noticeReceivers.ReceiverChannels
			}

			if noticeReceivers.StartTime != nil {
				noticeReceiversMap["start_time"] = noticeReceivers.StartTime
			}

			if noticeReceivers.EndTime != nil {
				noticeReceiversMap["end_time"] = noticeReceivers.EndTime
			}

			if noticeReceivers.Index != nil {
				noticeReceiversMap["index"] = noticeReceivers.Index
			}

			noticeReceiversList = append(noticeReceiversList, noticeReceiversMap)
		}

		_ = d.Set("notice_receivers", noticeReceiversList)
	}

	webCallbacksList := make([]map[string]interface{}, 0, len(respData.WebCallbacks))
	if respData.WebCallbacks != nil {
		for _, webCallbacks := range respData.WebCallbacks {
			webCallbacksMap := map[string]interface{}{}

			if webCallbacks.Url != nil {
				webCallbacksMap["url"] = webCallbacks.Url
			}

			if webCallbacks.CallbackType != nil {
				webCallbacksMap["callback_type"] = webCallbacks.CallbackType
			}

			if webCallbacks.Method != nil {
				webCallbacksMap["method"] = webCallbacks.Method
			}

			if webCallbacks.Headers != nil {
				webCallbacksMap["headers"] = webCallbacks.Headers
			}

			if webCallbacks.Body != nil {
				webCallbacksMap["body"] = webCallbacks.Body
			}

			if webCallbacks.Index != nil {
				webCallbacksMap["index"] = webCallbacks.Index
			}

			webCallbacksList = append(webCallbacksList, webCallbacksMap)
		}

		_ = d.Set("web_callbacks", webCallbacksList)
	}

	tcClient := meta.(tccommon.ProviderMeta).GetAPIV3Conn()
	tagService := svctag.NewTagService(tcClient)
	tags, err := tagService.DescribeResourceTags(ctx, "cls", "alarmNotice", tcClient.Region, d.Id())
	if err != nil {
		return err
	}
	_ = d.Set("tags", tags)

	return nil
}

func resourceTencentCloudClsAlarmNoticeUpdate(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_cls_alarm_notice.update")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)

	alarmNoticeId := d.Id()

	needChange := false
	mutableArgs := []string{"name", "type", "notice_receivers", "web_callbacks"}
	for _, v := range mutableArgs {
		if d.HasChange(v) {
			needChange = true
			break
		}
	}

	if needChange {
		request := cls.NewModifyAlarmNoticeRequest()

		request.AlarmNoticeId = &alarmNoticeId

		if v, ok := d.GetOk("name"); ok {
			request.Name = helper.String(v.(string))
		}

		if v, ok := d.GetOk("type"); ok {
			request.Type = helper.String(v.(string))
		}

		if v, ok := d.GetOk("notice_receivers"); ok {
			for _, item := range v.([]interface{}) {
				noticeReceiversMap := item.(map[string]interface{})
				noticeReceiver := cls.NoticeReceiver{}
				if v, ok := noticeReceiversMap["receiver_type"]; ok {
					noticeReceiver.ReceiverType = helper.String(v.(string))
				}
				if v, ok := noticeReceiversMap["receiver_ids"]; ok {
					receiverIdsSet := v.(*schema.Set).List()
					for i := range receiverIdsSet {
						receiverIds := receiverIdsSet[i].(int)
						noticeReceiver.ReceiverIds = append(noticeReceiver.ReceiverIds, helper.IntInt64(receiverIds))
					}
				}
				if v, ok := noticeReceiversMap["receiver_channels"]; ok {
					receiverChannelsSet := v.(*schema.Set).List()
					for i := range receiverChannelsSet {
						receiverChannels := receiverChannelsSet[i].(string)
						noticeReceiver.ReceiverChannels = append(noticeReceiver.ReceiverChannels, helper.String(receiverChannels))
					}
				}
				if v, ok := noticeReceiversMap["start_time"]; ok {
					noticeReceiver.StartTime = helper.String(v.(string))
				}
				if v, ok := noticeReceiversMap["end_time"]; ok {
					noticeReceiver.EndTime = helper.String(v.(string))
				}
				if v, ok := noticeReceiversMap["index"]; ok {
					noticeReceiver.Index = helper.IntInt64(v.(int))
				}
				request.NoticeReceivers = append(request.NoticeReceivers, &noticeReceiver)
			}
		}

		if v, ok := d.GetOk("web_callbacks"); ok {
			for _, item := range v.([]interface{}) {
				webCallbacksMap := item.(map[string]interface{})
				webCallback := cls.WebCallback{}
				if v, ok := webCallbacksMap["url"]; ok {
					webCallback.Url = helper.String(v.(string))
				}
				if v, ok := webCallbacksMap["callback_type"]; ok {
					webCallback.CallbackType = helper.String(v.(string))
				}
				if v, ok := webCallbacksMap["method"]; ok {
					webCallback.Method = helper.String(v.(string))
				}
				if v, ok := webCallbacksMap["headers"]; ok {
					headersSet := v.(*schema.Set).List()
					for i := range headersSet {
						headers := headersSet[i].(string)
						webCallback.Headers = append(webCallback.Headers, helper.String(headers))
					}
				}
				if v, ok := webCallbacksMap["body"]; ok {
					webCallback.Body = helper.String(v.(string))
				}
				if v, ok := webCallbacksMap["index"]; ok {
					webCallback.Index = helper.IntInt64(v.(int))
				}
				request.WebCallbacks = append(request.WebCallbacks, &webCallback)
			}
		}

		err := resource.Retry(tccommon.WriteRetryTimeout, func() *resource.RetryError {
			result, e := meta.(tccommon.ProviderMeta).GetAPIV3Conn().UseClsClient().ModifyAlarmNotice(request)
			if e != nil {
				return tccommon.RetryError(e)
			} else {
				log.Printf("[DEBUG]%s api[%s] success, request body [%s], response body [%s]\n", logId, request.GetAction(), request.ToJsonString(), result.ToJsonString())
			}
			return nil
		})
		if err != nil {
			log.Printf("[CRITAL]%s update cls alarm notice failed, reason:%+v", logId, err)
			return err
		}
	}

	if d.HasChange("tags") {
		ctx := context.WithValue(context.TODO(), tccommon.LogIdKey, logId)
		tcClient := meta.(tccommon.ProviderMeta).GetAPIV3Conn()
		tagService := svctag.NewTagService(tcClient)
		oldTags, newTags := d.GetChange("tags")
		replaceTags, deleteTags := svctag.DiffTags(oldTags.(map[string]interface{}), newTags.(map[string]interface{}))
		resourceName := tccommon.BuildTagResourceName("cls", "alarmNotice", tcClient.Region, d.Id())
		if err := tagService.ModifyTags(ctx, resourceName, replaceTags, deleteTags); err != nil {
			return err
		}
	}

	return resourceTencentCloudClsAlarmNoticeRead(d, meta)
}

func resourceTencentCloudClsAlarmNoticeDelete(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_cls_alarm_notice.delete")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)
	ctx := context.WithValue(context.TODO(), tccommon.LogIdKey, logId)

	service := ClsService{client: meta.(tccommon.ProviderMeta).GetAPIV3Conn()}

	alarmNoticeId := d.Id()

	if err := service.DeleteClsAlarmNoticeById(ctx, alarmNoticeId); err != nil {
		return err
	}

	return nil
}
