// Code generated by iacg; DO NOT EDIT.
package cls

import (
	"context"
	"fmt"
	"log"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	cls "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cls/v20201016"

	tccommon "github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/common"
	"github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/internal/helper"
)

func ResourceTencentCloudClsCkafkaConsumer() *schema.Resource {
	return &schema.Resource{
		Create: resourceTencentCloudClsCkafkaConsumerCreate,
		Read:   resourceTencentCloudClsCkafkaConsumerRead,
		Update: resourceTencentCloudClsCkafkaConsumerUpdate,
		Delete: resourceTencentCloudClsCkafkaConsumerDelete,
		Importer: &schema.ResourceImporter{
			State: schema.ImportStatePassthrough,
		},
		Schema: map[string]*schema.Schema{
			"topic_id": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: "topic id.",
			},

			"need_content": {
				Type:        schema.TypeBool,
				Optional:    true,
				Description: "whether to deliver the metadata information of the log.",
			},

			"content": {
				Type:        schema.TypeList,
				Optional:    true,
				MaxItems:    1,
				Description: "metadata information.",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"enable_tag": {
							Type:        schema.TypeBool,
							Required:    true,
							Description: "whether to deliver the TAG info.",
						},
						"meta_fields": {
							Type:        schema.TypeSet,
							Required:    true,
							Description: "metadata info list.",
							Elem: &schema.Schema{
								Type: schema.TypeString,
							},
						},
						"tag_json_not_tiled": {
							Type:        schema.TypeBool,
							Optional:    true,
							Description: "whether to tiling tag json.",
						},
						"timestamp_accuracy": {
							Type:        schema.TypeInt,
							Optional:    true,
							Description: "delivery timestamp precision,1 for second, 2 for millisecond.",
						},
					},
				},
			},

			"ckafka": {
				Type:        schema.TypeList,
				Optional:    true,
				MaxItems:    1,
				Description: "ckafka info.",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"vip": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "vip.",
						},
						"vport": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "vport.",
						},
						"instance_id": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "instance id.",
						},
						"instance_name": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "instance name.",
						},
						"topic_id": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "topic id of ckafka.",
						},
						"topic_name": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "topic name of ckafka.",
						},
					},
				},
			},

			"compression": {
				Type:        schema.TypeInt,
				Optional:    true,
				Description: "compression method. 0 for NONE, 2 for SNAPPY, 3 for LZ4.",
			},
		},
	}
}

func resourceTencentCloudClsCkafkaConsumerCreate(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_cls_ckafka_consumer.create")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)

	var (
		topicId string
	)
	var (
		request  = cls.NewCreateConsumerRequest()
		response = cls.NewCreateConsumerResponse()
	)

	if v, ok := d.GetOk("topic_id"); ok {
		topicId = v.(string)
	}

	if v, ok := d.GetOk("topic_id"); ok {
		request.TopicId = helper.String(v.(string))
	}

	if v, ok := d.GetOkExists("need_content"); ok {
		request.NeedContent = helper.Bool(v.(bool))
	}

	if contentMap, ok := helper.InterfacesHeadMap(d, "content"); ok {
		consumerContent := cls.ConsumerContent{}
		if v, ok := contentMap["enable_tag"]; ok {
			consumerContent.EnableTag = helper.Bool(v.(bool))
		}
		if v, ok := contentMap["meta_fields"]; ok {
			metaFieldsSet := v.(*schema.Set).List()
			for i := range metaFieldsSet {
				metaFields := metaFieldsSet[i].(string)
				consumerContent.MetaFields = append(consumerContent.MetaFields, helper.String(metaFields))
			}
		}
		if v, ok := contentMap["tag_json_not_tiled"]; ok {
			consumerContent.TagJsonNotTiled = helper.Bool(v.(bool))
		}
		if v, ok := contentMap["timestamp_accuracy"]; ok {
			consumerContent.TimestampAccuracy = helper.IntInt64(v.(int))
		}
		request.Content = &consumerContent
	}

	if ckafkaMap, ok := helper.InterfacesHeadMap(d, "ckafka"); ok {
		ckafka := cls.Ckafka{}
		if v, ok := ckafkaMap["vip"]; ok {
			ckafka.Vip = helper.String(v.(string))
		}
		if v, ok := ckafkaMap["vport"]; ok {
			ckafka.Vport = helper.String(v.(string))
		}
		if v, ok := ckafkaMap["instance_id"]; ok {
			ckafka.InstanceId = helper.String(v.(string))
		}
		if v, ok := ckafkaMap["instance_name"]; ok {
			ckafka.InstanceName = helper.String(v.(string))
		}
		if v, ok := ckafkaMap["topic_id"]; ok {
			ckafka.TopicId = helper.String(v.(string))
		}
		if v, ok := ckafkaMap["topic_name"]; ok {
			ckafka.TopicName = helper.String(v.(string))
		}
		request.Ckafka = &ckafka
	}

	if v, ok := d.GetOkExists("compression"); ok {
		request.Compression = helper.IntInt64(v.(int))
	}

	err := resource.Retry(tccommon.WriteRetryTimeout, func() *resource.RetryError {
		result, e := meta.(tccommon.ProviderMeta).GetAPIV3Conn().UseClsClient().CreateConsumer(request)
		if e != nil {
			return tccommon.RetryError(e)
		} else {
			log.Printf("[DEBUG]%s api[%s] success, request body [%s], response body [%s]\n", logId, request.GetAction(), request.ToJsonString(), result.ToJsonString())
		}
		response = result
		return nil
	})
	if err != nil {
		log.Printf("[CRITAL]%s create cls ckafka consumer failed, reason:%+v", logId, err)
		return err
	}

	_ = response
	d.SetId(topicId)

	return resourceTencentCloudClsCkafkaConsumerRead(d, meta)
}

func resourceTencentCloudClsCkafkaConsumerRead(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_cls_ckafka_consumer.read")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)

	ctx := context.WithValue(context.TODO(), tccommon.LogIdKey, logId)

	service := ClsService{client: meta.(tccommon.ProviderMeta).GetAPIV3Conn()}

	topicId := d.Id()

	_ = d.Set("topic_id", topicId)

	respData, err := service.DescribeClsCkafkaConsumerById(ctx, topicId)
	if err != nil {
		return err
	}

	if respData == nil {
		d.SetId("")
		log.Printf("[WARN]%s resource `cls_ckafka_consumer` [%s] not found, please check if it has been deleted.\n", logId, d.Id())
		return nil
	}
	if respData.NeedContent != nil {
		_ = d.Set("need_content", respData.NeedContent)
	}

	contentMap := map[string]interface{}{}

	if respData.Content != nil {
		if respData.Content.EnableTag != nil {
			contentMap["enable_tag"] = respData.Content.EnableTag
		}

		if respData.Content.MetaFields != nil {
			contentMap["meta_fields"] = respData.Content.MetaFields
		}

		if respData.Content.TagJsonNotTiled != nil {
			contentMap["tag_json_not_tiled"] = respData.Content.TagJsonNotTiled
		}

		if respData.Content.TimestampAccuracy != nil {
			contentMap["timestamp_accuracy"] = respData.Content.TimestampAccuracy
		}

		_ = d.Set("content", []interface{}{contentMap})
	}

	ckafkaMap := map[string]interface{}{}

	if respData.Ckafka != nil {
		if respData.Ckafka.Vip != nil {
			ckafkaMap["vip"] = respData.Ckafka.Vip
		}

		if respData.Ckafka.Vport != nil {
			ckafkaMap["vport"] = respData.Ckafka.Vport
		}

		if respData.Ckafka.InstanceId != nil {
			ckafkaMap["instance_id"] = respData.Ckafka.InstanceId
		}

		if respData.Ckafka.InstanceName != nil {
			ckafkaMap["instance_name"] = respData.Ckafka.InstanceName
		}

		if respData.Ckafka.TopicId != nil {
			ckafkaMap["topic_id"] = respData.Ckafka.TopicId
		}

		if respData.Ckafka.TopicName != nil {
			ckafkaMap["topic_name"] = respData.Ckafka.TopicName
		}

		_ = d.Set("ckafka", []interface{}{ckafkaMap})
	}

	if respData.Compression != nil {
		_ = d.Set("compression", respData.Compression)
	}

	return nil
}

func resourceTencentCloudClsCkafkaConsumerUpdate(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_cls_ckafka_consumer.update")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)

	immutableArgs := []string{"topic_id"}
	for _, v := range immutableArgs {
		if d.HasChange(v) {
			return fmt.Errorf("argument `%s` cannot be changed", v)
		}
	}
	topicId := d.Id()

	needChange := false
	mutableArgs := []string{"need_content", "content", "ckafka", "compression"}
	for _, v := range mutableArgs {
		if d.HasChange(v) {
			needChange = true
			break
		}
	}

	if needChange {
		request := cls.NewModifyConsumerRequest()

		request.TopicId = &topicId

		if v, ok := d.GetOkExists("need_content"); ok {
			request.NeedContent = helper.Bool(v.(bool))
		}

		if contentMap, ok := helper.InterfacesHeadMap(d, "content"); ok {
			consumerContent := cls.ConsumerContent{}
			if v, ok := contentMap["enable_tag"]; ok {
				consumerContent.EnableTag = helper.Bool(v.(bool))
			}
			if v, ok := contentMap["meta_fields"]; ok {
				metaFieldsSet := v.(*schema.Set).List()
				for i := range metaFieldsSet {
					metaFields := metaFieldsSet[i].(string)
					consumerContent.MetaFields = append(consumerContent.MetaFields, helper.String(metaFields))
				}
			}
			if v, ok := contentMap["tag_json_not_tiled"]; ok {
				consumerContent.TagJsonNotTiled = helper.Bool(v.(bool))
			}
			if v, ok := contentMap["timestamp_accuracy"]; ok {
				consumerContent.TimestampAccuracy = helper.IntInt64(v.(int))
			}
			request.Content = &consumerContent
		}

		if ckafkaMap, ok := helper.InterfacesHeadMap(d, "ckafka"); ok {
			ckafka := cls.Ckafka{}
			if v, ok := ckafkaMap["vip"]; ok {
				ckafka.Vip = helper.String(v.(string))
			}
			if v, ok := ckafkaMap["vport"]; ok {
				ckafka.Vport = helper.String(v.(string))
			}
			if v, ok := ckafkaMap["instance_id"]; ok {
				ckafka.InstanceId = helper.String(v.(string))
			}
			if v, ok := ckafkaMap["instance_name"]; ok {
				ckafka.InstanceName = helper.String(v.(string))
			}
			if v, ok := ckafkaMap["topic_id"]; ok {
				ckafka.TopicId = helper.String(v.(string))
			}
			if v, ok := ckafkaMap["topic_name"]; ok {
				ckafka.TopicName = helper.String(v.(string))
			}
			request.Ckafka = &ckafka
		}

		if v, ok := d.GetOkExists("compression"); ok {
			request.Compression = helper.IntInt64(v.(int))
		}

		err := resource.Retry(tccommon.WriteRetryTimeout, func() *resource.RetryError {
			result, e := meta.(tccommon.ProviderMeta).GetAPIV3Conn().UseClsClient().ModifyConsumer(request)
			if e != nil {
				return tccommon.RetryError(e)
			} else {
				log.Printf("[DEBUG]%s api[%s] success, request body [%s], response body [%s]\n", logId, request.GetAction(), request.ToJsonString(), result.ToJsonString())
			}
			return nil
		})
		if err != nil {
			log.Printf("[CRITAL]%s update cls ckafka consumer failed, reason:%+v", logId, err)
			return err
		}
	}

	return resourceTencentCloudClsCkafkaConsumerRead(d, meta)
}

func resourceTencentCloudClsCkafkaConsumerDelete(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_cls_ckafka_consumer.delete")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)
	ctx := context.WithValue(context.TODO(), tccommon.LogIdKey, logId)

	service := ClsService{client: meta.(tccommon.ProviderMeta).GetAPIV3Conn()}

	topicId := d.Id()

	if err := service.DeleteClsCkafkaConsumerById(ctx, topicId); err != nil {
		return err
	}

	return nil
}
