package ccn

const CNN_QOS_PT = "PT"
const CNN_QOS_AU = "AU"
const CNN_QOS_AG = "AG"

const CNN_INSTANCE_TYPE_VPC = "VPC"
const CNN_INSTANCE_TYPE_DIRECTCONNECT = "DIRECTCONNECT"
const CNN_INSTANCE_TYPE_BMVPC = "BMVPC"
const CNN_INSTANCE_TYPE_VPNGW = "VPNGW"

const PREPAID = "PREPAID"
const POSTPAID = "POSTPAID"

const OuterRegionLimit = "OUTER_REGION_LIMIT"
const InterRegionLimit = "INTER_REGION_LIMIT"
