package thpc

const (
	SPACE_STATE_ONLINE  = "ONLINE"
	SPACE_STATE_ARREARS = "ARREARS"
)

const (
	SPACE_CHARGE_TYPE_PREPAID    = "PREPAID"
	SPACE_CHARGE_TYPE_UNDERWRITE = "UNDERWRITE"
)

var SPACE_CHARGE_TYPE = []string{
	SPACE_CHARGE_TYPE_PREPAID,
	SPACE_CHARGE_TYPE_UNDERWRITE,
}

const (
	CVM_DISK_TYPE_LOCAL_NVME    = "LOCAL_NVME"
	CVM_DISK_TYPE_LOCAL_BASIC   = "LOCAL_BASIC"
	CVM_DISK_TYPE_LOCAL_SSD     = "LOCAL_SSD"
	CVM_DISK_TYPE_CLOUD_BASIC   = "CLOUD_BASIC"
	CVM_DISK_TYPE_CLOUD_SSD     = "CLOUD_SSD"
	CVM_DISK_TYPE_CLOUD_PREMIUM = "CLOUD_PREMIUM"
	CVM_DISK_TYPE_CLOUD_BSSD    = "CLOUD_BSSD"
	CVM_DISK_TYPE_CLOUD_HSSD    = "CLOUD_HSSD"
	CVM_DISK_TYPE_CLOUD_TSSD    = "CLOUD_TSSD"
)

var SYSTEM_DISK_TYPE = []string{
	CVM_DISK_TYPE_LOCAL_BASIC,
	CVM_DISK_TYPE_LOCAL_SSD,
	CVM_DISK_TYPE_CLOUD_BASIC,
	CVM_DISK_TYPE_CLOUD_SSD,
	CVM_DISK_TYPE_CLOUD_PREMIUM,
	CVM_DISK_TYPE_CLOUD_BSSD,
	CVM_DISK_TYPE_CLOUD_HSSD,
	CVM_DISK_TYPE_CLOUD_TSSD,
}

const (
	CVM_INSTANCE_STATE_FAILED    = "FAILED"
	CVM_INSTANCE_STATE_OPERATING = "OPERATING"
)
