package thpc

const (
	SPACE_STATE_ONLINE  = "ONLINE"
	SPACE_STATE_ARREARS = "ARREARS"
)

const (
	SPACE_CHARGE_TYPE_PREPAID    = "PREPAID"
	SPACE_CHARGE_TYPE_UNDERWRITE = "UNDERWRITE"
)

var SPACE_CHARGE_TYPE = []string{
	SPACE_CHARGE_TYPE_PREPAID,
	SPACE_CHARGE_TYPE_UNDERWRITE,
}
