package kms

const (
	KMS_ORIGIN_TENCENT_KMS = "TENCENT_KMS"
	KMS_ORIGIN_EXTERNAL    = "EXTERNAL"
	KMS_ORIGIN_ALL         = "ALL"
)

var KMS_ORIGIN_TYPE = map[string]uint64{
	KMS_ORIGIN_TENCENT_KMS: 1,
	KMS_ORIGIN_EXTERNAL:    2,
}

const (
	KMS_KEY_USAGE_ALL                             = "ALL"
	KMS_KEY_USAGE_ENCRYPT_DECRYPT                 = "ENCRYPT_DECRYPT"
	KMS_KEY_USAGE_ASYMMETRIC_DECRYPT_RSA_2048     = "ASYMMETRIC_DECRYPT_RSA_2048"
	KMS_KEY_USAGE_ASYMMETRIC_DECRYPT_SM2          = "ASYMMETRIC_DECRYPT_SM2"
	KMS_KEY_USAGE_ASYMMETRIC_SIGN_VERIFY_SM2      = "ASYMMETRIC_SIGN_VERIFY_SM2"
	KMS_KEY_USAGE_ASYMMETRIC_SIGN_VERIFY_RSA_2048 = "ASYMMETRIC_SIGN_VERIFY_RSA_2048"
	KMS_KEY_USAGE_ASYMMETRIC_SIGN_VERIFY_ECC      = "ASYMMETRIC_SIGN_VERIFY_ECC"
)

const (
	KMS_PAGE_LIMIT = 200
)

const (
	KMS_WRAPPING_ALGORITHM_RSAES_PKCS1_V1_5   = "RSAES_PKCS1_V1_5"
	KMS_WRAPPING_ALGORITHM_RSAES_OAEP_SHA_1   = "RSAES_OAEP_SHA_1"
	KMS_WRAPPING_ALGORITHM_RSAES_OAEP_SHA_256 = "RSAES_OAEP_SHA_256"
)

const (
	KMS_WRAPPING_KEY_SPEC_RSA_2048 = "RSA_2048"
)

const (
	KMS_KEY_STATE_ALL           = "All"
	KMS_KEY_STATE_ENABLED       = "Enabled"
	KMS_KEY_STATE_DISABLED      = "Disabled"
	KMS_KEY_STATE_PENDINGDELETE = "PendingDelete"
	KMS_KEY_STATE_PENDINGIMPORT = "PendingImport"
	KMS_KEY_STATE_ARCHIVED      = "Archived"
)

var KMS_RETRYABLE_ERROR = []string{
	// client
	"ClientError.NetworkError",
	"ClientError.HttpStatusCodeError",
}

const (
	WHITE_BOX_KEY_ALGORITHM_AES_256 = "AES_256"
	WHITE_BOX_KEY_ALGORITHM_SM4     = "SM4"
)

var WHITE_BOX_KEY_ALGORITHM = []string{
	WHITE_BOX_KEY_ALGORITHM_AES_256,
	WHITE_BOX_KEY_ALGORITHM_SM4,
}

const (
	WHITE_BOX_KEY_STATUS_ENABLED  = "Enabled"
	WHITE_BOX_KEY_STATUS_DISABLED = "Disabled"
)

var WHITE_BOX_KEY_STATUS = []string{
	WHITE_BOX_KEY_STATUS_ENABLED,
	WHITE_BOX_KEY_STATUS_DISABLED,
}
