// Code generated by iacg; DO NOT EDIT.
package teo

import (
	"context"
	"fmt"
	"log"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	tccommon "github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/common"
	"github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/internal/helper"
)

func DataSourceTencentCloudTeoL7AccRule() *schema.Resource {
	return &schema.Resource{
		Read: dataSourceTencentCloudTeoL7AccRuleRead,
		Schema: map[string]*schema.Schema{
			"zone_id": {
				Type:        schema.TypeString,
				Required:    true,
				Description: "Zone id.",
			},

			"total_count": {
				Type:        schema.TypeInt,
				Computed:    true,
				Description: "Total count of L7 acceleration rules.",
			},

			"rules": {
				Type:        schema.TypeList,
				Computed:    true,
				Description: "Rules content.",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"rule_id": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "Rule ID. Unique identifier of the rule.",
						},
						"rule_name": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "Rule name. The name length limit is 255 characters.",
						},
						"description": {
							Type:        schema.TypeList,
							Computed:    true,
							Description: "Rule annotation. multiple annotations can be added.",
							Elem: &schema.Schema{
								Type: schema.TypeString,
							},
						},
						"rule_priority": {
							Type:        schema.TypeInt,
							Computed:    true,
							Description: "Rule priority. only used as an output parameter.",
						},
						"branches": {
							Type:        schema.TypeList,
							Computed:    true,
							Description: "Sub-Rule branch. this list currently supports filling in only one rule; multiple entries are invalid.",
							Elem: &schema.Resource{
								Schema: TencentTeoL7RuleBranchBasicInfo(1),
							},
						},
					},
				},
			},
		},
	}
}

func dataSourceTencentCloudTeoL7AccRuleRead(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("data_source.tencentcloud_teo_l7_acc_rule.read")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)

	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	service := TeoService{client: meta.(tccommon.ProviderMeta).GetAPIV3Conn()}

	zoneId := d.Get("zone_id").(string)

	d.SetId(zoneId)

	respData, err := service.DescribeTeoL7AccRuleById(ctx, zoneId, "")
	if err != nil {
		return err
	}

	if respData == nil {
		return fmt.Errorf("data source `teo_l7_acc_rule` [%s] not found", zoneId)
	}

	// Set total_count field
	if respData.TotalCount != nil {
		_ = d.Set("total_count", *respData.TotalCount)
	} else {
		_ = d.Set("total_count", 0)
	}

	rulesList := make([]map[string]interface{}, 0, len(respData.Rules))
	if respData.Rules != nil {
		for _, rules := range respData.Rules {
			rulesMap := map[string]interface{}{}

			if rules.RuleId != nil {
				rulesMap["rule_id"] = rules.RuleId
			}

			if rules.RuleName != nil {
				rulesMap["rule_name"] = rules.RuleName
			}

			if rules.Description != nil {
				rulesMap["description"] = rules.Description
			}

			if rules.RulePriority != nil {
				rulesMap["rule_priority"] = rules.RulePriority
			}

			if rules.Branches != nil {
				rulesMap["branches"] = resourceTencentCloudTeoL7AccRuleSetBranchs(rules.Branches)
			}
			rulesList = append(rulesList, rulesMap)
		}
	}

	_ = d.Set("rules", rulesList)

	_ = zoneId
	return nil
}
