// Code generated by iacg; DO NOT EDIT.
package teo

import (
	"context"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	teov20220901 "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/teo/v20220901"
	tccommon "github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/common"
	"github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/internal/helper"
)

func DataSourceTencentCloudTeoRealtimeLogDeliveryTasks() *schema.Resource {
	return &schema.Resource{
		Read: dataSourceTencentCloudTeoRealtimeLogDeliveryTasksRead,
		Schema: map[string]*schema.Schema{
			"filters": {
				Type:        schema.TypeList,
				Optional:    true,
				Description: "Filter criteria. Supported filter fields: zone-id, task-id, task-name, task-type.",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"name": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Field to be filtered.",
						},
						"values": {
							Type:        schema.TypeSet,
							Required:    true,
							Description: "Value of the filtered field.",
							Elem: &schema.Schema{
								Type: schema.TypeString,
							},
						},
						"fuzzy": {
							Type:        schema.TypeBool,
							Optional:    true,
							Description: "Whether to enable fuzzy query.",
						},
					},
				},
			},

			"offset": {
				Type:        schema.TypeInt,
				Optional:    true,
				Default:     0,
				Description: "Offset of the query result.",
			},

			"limit": {
				Type:        schema.TypeInt,
				Optional:    true,
				Default:     20,
				Description: "Limit on the number of query results.",
			},

			"order": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "Sort field, e.g., task-id, task-name.",
			},

			"direction": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "Sort direction: asc or desc.",
			},

			"realtime_log_delivery_tasks": {
				Type:        schema.TypeList,
				Computed:    true,
				Description: "List of realtime log delivery tasks.",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"task_id": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "Task ID.",
						},
						"zone_id": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "ID of the site.",
						},
						"task_name": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "The name of the real-time log delivery task.",
						},
						"task_type": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "The real-time log delivery task type. Values: `cls`, `custom_endpoint`, `s3`.",
						},
						"delivery_status": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "The delivery status of the task.",
						},
						"log_type": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "Data delivery type.",
						},
						"area": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "Data delivery area. Values: `mainland`, `overseas`.",
						},
						"entity_list": {
							Type:        schema.TypeList,
							Computed:    true,
							Description: "List of entities corresponding to real-time log delivery tasks.",
							Elem: &schema.Schema{
								Type: schema.TypeString,
							},
						},
						"fields": {
							Type:        schema.TypeList,
							Computed:    true,
							Description: "A list of preset fields for delivery.",
							Elem: &schema.Schema{
								Type: schema.TypeString,
							},
						},
						"custom_fields": {
							Type:        schema.TypeList,
							Computed:    true,
							Description: "The list of custom fields delivered.",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"name": {
										Type:        schema.TypeString,
										Computed:    true,
										Description: "Extract data from the specified location. Values: `ReqHeader`, `RspHeader`, `Cookie`.",
									},
									"value": {
										Type:        schema.TypeString,
										Computed:    true,
										Description: "The name of the parameter whose value needs to be extracted.",
									},
									"enabled": {
										Type:        schema.TypeBool,
										Computed:    true,
										Description: "Whether to deliver this field.",
									},
								},
							},
						},
						"sample": {
							Type:        schema.TypeInt,
							Computed:    true,
							Description: "Sampling ratio (1-100).",
						},
					},
				},
			},

			"result_output_file": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "Used to save results.",
			},
		},
	}
}

func dataSourceTencentCloudTeoRealtimeLogDeliveryTasksRead(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("data_source.tencentcloud_teo_realtime_log_delivery_tasks.read")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(nil)
	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	service := TeoService{client: meta.(tccommon.ProviderMeta).GetAPIV3Conn()}

	// Extract and build filters
	filters := make([]*teov20220901.AdvancedFilter, 0)
	if v, ok := d.GetOk("filters"); ok {
		filtersSet := v.([]interface{})
		for _, item := range filtersSet {
			filtersMap := item.(map[string]interface{})
			advancedFilter := teov20220901.AdvancedFilter{}
			if v, ok := filtersMap["name"].(string); ok && v != "" {
				advancedFilter.Name = helper.String(v)
			}
			if v, ok := filtersMap["values"]; ok {
				valuesSet := v.(*schema.Set).List()
				for i := range valuesSet {
					values := valuesSet[i].(string)
					advancedFilter.Values = append(advancedFilter.Values, helper.String(values))
				}
			}
			if v, ok := filtersMap["fuzzy"].(bool); ok {
				advancedFilter.Fuzzy = helper.Bool(v)
			}
			filters = append(filters, &advancedFilter)
		}
	}

	// Extract pagination and sorting parameters
	offset := uint64(d.Get("offset").(int))
	limit := uint64(d.Get("limit").(int))
	order := d.Get("order").(string)
	direction := d.Get("direction").(string)

	// Call service layer function
	var tasks []*teov20220901.RealtimeLogDeliveryTask
	var total int64
	reqErr := resource.Retry(tccommon.ReadRetryTimeout, func() *resource.RetryError {
		result, t, e := service.DescribeTeoRealtimeLogDeliveryTasks(ctx, filters, offset, limit, order, direction)
		if e != nil {
			return tccommon.RetryError(e)
		}
		tasks = result
		total = t
		return nil
	})
	if reqErr != nil {
		return reqErr
	}

	// Handle empty result sets gracefully
	tasksList := make([]map[string]interface{}, 0, len(tasks))
	var taskIds []string
	if tasks != nil {
		for _, task := range tasks {
			taskMap := map[string]interface{}{}

			if task.TaskId != nil {
				taskMap["task_id"] = task.TaskId
				taskIds = append(taskIds, *task.TaskId)
			}

			if task.ZoneId != nil {
				taskMap["zone_id"] = task.ZoneId
			}

			if task.TaskName != nil {
				taskMap["task_name"] = task.TaskName
			}

			if task.TaskType != nil {
				taskMap["task_type"] = task.TaskType
			}

			if task.DeliveryStatus != nil {
				taskMap["delivery_status"] = task.DeliveryStatus
			}

			if task.LogType != nil {
				taskMap["log_type"] = task.LogType
			}

			if task.Area != nil {
				taskMap["area"] = task.Area
			}

			if task.EntityList != nil {
				taskMap["entity_list"] = task.EntityList
			}

			if task.Fields != nil {
				taskMap["fields"] = task.Fields
			}

			customFieldsList := make([]map[string]interface{}, 0, len(task.CustomFields))
			if task.CustomFields != nil {
				for _, customFields := range task.CustomFields {
					customFieldsMap := map[string]interface{}{}

					if customFields.Name != nil {
						customFieldsMap["name"] = customFields.Name
					}

					if customFields.Value != nil {
						customFieldsMap["value"] = customFields.Value
					}

					if customFields.Enabled != nil {
						customFieldsMap["enabled"] = customFields.Enabled
					}

					customFieldsList = append(customFieldsList, customFieldsMap)
				}

				taskMap["custom_fields"] = customFieldsList
			}

			if task.Sample != nil {
				taskMap["sample"] = task.Sample
			}

			tasksList = append(tasksList, taskMap)
		}

		_ = d.Set("realtime_log_delivery_tasks", tasksList)
	}

	// Set computed fields in Terraform state
	d.SetId(helper.DataResourceIdsHash(taskIds))

	// Write result to output file if specified
	output, ok := d.GetOk("result_output_file")
	if ok && output.(string) != "" {
		if e := tccommon.WriteToFile(output.(string), tasksList); e != nil {
			return e
		}
	}

	return nil
}
