package teo

import (
	"context"
	"fmt"
	"log"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	teov20220901 "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/teo/v20220901"

	tccommon "github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/common"
	"github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/internal/helper"
)

func ResourceTencentCloudTeoSecurityApiResource() *schema.Resource {
	return &schema.Resource{
		Create: resourceTencentCloudTeoSecurityApiResourceCreate,
		Read:   resourceTencentCloudTeoSecurityApiResourceRead,
		Update: resourceTencentCloudTeoSecurityApiResourceUpdate,
		Delete: resourceTencentCloudTeoSecurityApiResourceDelete,
		Importer: &schema.ResourceImporter{
			State: schema.ImportStatePassthrough,
		},
		Schema: map[string]*schema.Schema{
			"zone_id": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: "Site ID.",
			},

			"api_resources": {
				Type:        schema.TypeList,
				Required:    true,
				Description: "API resource list.",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"id": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "API resource ID, generated by server on creation.",
						},
						"name": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "API resource name.",
						},
						"api_service_ids": {
							Type:        schema.TypeList,
							Optional:    true,
							Description: "API service IDs associated with the API resource.",
							Elem: &schema.Schema{
								Type: schema.TypeString,
							},
						},
						"path": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "Resource path.",
						},
						"methods": {
							Type:        schema.TypeList,
							Optional:    true,
							Description: "Request method list. Supported values: GET, POST, PUT, HEAD, PATCH, OPTIONS, DELETE.",
							Elem: &schema.Schema{
								Type: schema.TypeString,
							},
						},
						"request_constraint": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "Request content matching rule, must conform to expression syntax.",
						},
					},
				},
			},

			"api_resource_ids": {
				Type:        schema.TypeList,
				Computed:    true,
				Description: "API resource IDs returned by server after creation.",
				Elem: &schema.Schema{
					Type: schema.TypeString,
				},
			},
		},
	}
}

func resourceTencentCloudTeoSecurityApiResourceCreate(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_teo_security_api_resource.create")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)
	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	var (
		request  = teov20220901.NewCreateSecurityAPIResourceRequest()
		response = teov20220901.NewCreateSecurityAPIResourceResponse()
		zoneId   string
	)

	if v, ok := d.GetOk("zone_id"); ok {
		zoneId = v.(string)
		request.ZoneId = helper.String(zoneId)
	}

	if v, ok := d.GetOk("api_resources"); ok {
		for _, item := range v.([]interface{}) {
			apiResourceMap := item.(map[string]interface{})
			apiResource := teov20220901.APIResource{}
			if v, ok := apiResourceMap["name"].(string); ok && v != "" {
				apiResource.Name = helper.String(v)
			}
			if v, ok := apiResourceMap["api_service_ids"]; ok {
				apiServiceIds := v.([]interface{})
				for _, id := range apiServiceIds {
					apiResource.APIServiceIds = append(apiResource.APIServiceIds, helper.String(id.(string)))
				}
			}
			if v, ok := apiResourceMap["path"].(string); ok && v != "" {
				apiResource.Path = helper.String(v)
			}
			if v, ok := apiResourceMap["methods"]; ok {
				methods := v.([]interface{})
				for _, m := range methods {
					apiResource.Methods = append(apiResource.Methods, helper.String(m.(string)))
				}
			}
			if v, ok := apiResourceMap["request_constraint"].(string); ok && v != "" {
				apiResource.RequestConstraint = helper.String(v)
			}
			request.APIResources = append(request.APIResources, &apiResource)
		}
	}

	err := resource.Retry(tccommon.WriteRetryTimeout, func() *resource.RetryError {
		result, e := meta.(tccommon.ProviderMeta).GetAPIV3Conn().UseTeoV20220901Client().CreateSecurityAPIResourceWithContext(ctx, request)
		if e != nil {
			return tccommon.RetryError(e)
		} else {
			log.Printf("[DEBUG]%s api[%s] success, request body [%s], response body [%s]\n", logId, request.GetAction(), request.ToJsonString(), result.ToJsonString())
		}
		response = result
		return nil
	})
	if err != nil {
		log.Printf("[CRITAL]%s create teo security api resource failed, reason:%+v", logId, err)
		return err
	}

	if response == nil || response.Response == nil {
		return fmt.Errorf("Create teo security api resource failed, Response is nil.")
	}

	if response.Response.APIResourceIds != nil {
		apiResourceIds := make([]string, 0, len(response.Response.APIResourceIds))
		for _, id := range response.Response.APIResourceIds {
			if id != nil {
				apiResourceIds = append(apiResourceIds, *id)
			}
		}
		_ = d.Set("api_resource_ids", apiResourceIds)
	}

	d.SetId(zoneId)

	return resourceTencentCloudTeoSecurityApiResourceRead(d, meta)
}

func resourceTencentCloudTeoSecurityApiResourceRead(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_teo_security_api_resource.read")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)
	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	service := TeoService{client: meta.(tccommon.ProviderMeta).GetAPIV3Conn()}

	zoneId := d.Id()

	_ = d.Set("zone_id", zoneId)

	respData, err := service.DescribeSecurityAPIResourceById(ctx, zoneId)
	if err != nil {
		return err
	}

	if respData == nil {
		d.SetId("")
		log.Printf("[WARN]%s resource `tencentcloud_teo_security_api_resource` [%s] not found, please check if it has been deleted.\n", logId, d.Id())
		return nil
	}

	apiResourcesList := make([]map[string]interface{}, 0, len(respData.APIResources))
	apiResourceIds := make([]string, 0, len(respData.APIResources))

	if respData.APIResources != nil {
		for _, apiRes := range respData.APIResources {
			apiResourceMap := map[string]interface{}{}

			if apiRes.Id != nil {
				apiResourceMap["id"] = *apiRes.Id
				apiResourceIds = append(apiResourceIds, *apiRes.Id)
			}

			if apiRes.Name != nil {
				apiResourceMap["name"] = *apiRes.Name
			}

			if apiRes.APIServiceIds != nil {
				apiServiceIds := make([]string, 0, len(apiRes.APIServiceIds))
				for _, id := range apiRes.APIServiceIds {
					if id != nil {
						apiServiceIds = append(apiServiceIds, *id)
					}
				}
				apiResourceMap["api_service_ids"] = apiServiceIds
			}

			if apiRes.Path != nil {
				apiResourceMap["path"] = *apiRes.Path
			}

			if apiRes.Methods != nil {
				methods := make([]string, 0, len(apiRes.Methods))
				for _, m := range apiRes.Methods {
					if m != nil {
						methods = append(methods, *m)
					}
				}
				apiResourceMap["methods"] = methods
			}

			if apiRes.RequestConstraint != nil {
				apiResourceMap["request_constraint"] = *apiRes.RequestConstraint
			}

			apiResourcesList = append(apiResourcesList, apiResourceMap)
		}
	}

	_ = d.Set("api_resources", apiResourcesList)
	_ = d.Set("api_resource_ids", apiResourceIds)

	return nil
}

func resourceTencentCloudTeoSecurityApiResourceUpdate(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_teo_security_api_resource.update")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)
	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	needChange := false
	mutableArgs := []string{"api_resources"}
	for _, v := range mutableArgs {
		if d.HasChange(v) {
			needChange = true
			break
		}
	}

	if needChange {
		zoneId := d.Get("zone_id").(string)

		request := teov20220901.NewModifySecurityAPIResourceRequest()
		request.ZoneId = helper.String(zoneId)

		if v, ok := d.GetOk("api_resources"); ok {
			for _, item := range v.([]interface{}) {
				apiResourceMap := item.(map[string]interface{})
				apiResource := teov20220901.APIResource{}
				if v, ok := apiResourceMap["id"].(string); ok && v != "" {
					apiResource.Id = helper.String(v)
				}
				if v, ok := apiResourceMap["name"].(string); ok && v != "" {
					apiResource.Name = helper.String(v)
				}
				if v, ok := apiResourceMap["api_service_ids"]; ok {
					apiServiceIds := v.([]interface{})
					for _, id := range apiServiceIds {
						apiResource.APIServiceIds = append(apiResource.APIServiceIds, helper.String(id.(string)))
					}
				}
				if v, ok := apiResourceMap["path"].(string); ok && v != "" {
					apiResource.Path = helper.String(v)
				}
				if v, ok := apiResourceMap["methods"]; ok {
					methods := v.([]interface{})
					for _, m := range methods {
						apiResource.Methods = append(apiResource.Methods, helper.String(m.(string)))
					}
				}
				if v, ok := apiResourceMap["request_constraint"].(string); ok && v != "" {
					apiResource.RequestConstraint = helper.String(v)
				}
				request.APIResources = append(request.APIResources, &apiResource)
			}
		}

		err := resource.Retry(tccommon.WriteRetryTimeout, func() *resource.RetryError {
			result, e := meta.(tccommon.ProviderMeta).GetAPIV3Conn().UseTeoV20220901Client().ModifySecurityAPIResourceWithContext(ctx, request)
			if e != nil {
				return tccommon.RetryError(e)
			} else {
				log.Printf("[DEBUG]%s api[%s] success, request body [%s], response body [%s]\n", logId, request.GetAction(), request.ToJsonString(), result.ToJsonString())
			}
			return nil
		})
		if err != nil {
			log.Printf("[CRITAL]%s update teo security api resource failed, reason:%+v", logId, err)
			return err
		}
	}

	return resourceTencentCloudTeoSecurityApiResourceRead(d, meta)
}

func resourceTencentCloudTeoSecurityApiResourceDelete(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_teo_security_api_resource.delete")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)
	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	var (
		request = teov20220901.NewDeleteSecurityAPIResourceRequest()
	)

	zoneId := d.Get("zone_id").(string)
	request.ZoneId = helper.String(zoneId)

	if v, ok := d.GetOk("api_resource_ids"); ok {
		apiResourceIds := v.([]interface{})
		for _, id := range apiResourceIds {
			request.APIResourceIds = append(request.APIResourceIds, helper.String(id.(string)))
		}
	}

	err := resource.Retry(tccommon.WriteRetryTimeout, func() *resource.RetryError {
		result, e := meta.(tccommon.ProviderMeta).GetAPIV3Conn().UseTeoV20220901Client().DeleteSecurityAPIResourceWithContext(ctx, request)
		if e != nil {
			return tccommon.RetryError(e)
		} else {
			log.Printf("[DEBUG]%s api[%s] success, request body [%s], response body [%s]\n", logId, request.GetAction(), request.ToJsonString(), result.ToJsonString())
		}
		return nil
	})
	if err != nil {
		log.Printf("[CRITAL]%s delete teo security api resource failed, reason:%+v", logId, err)
		return err
	}

	return nil
}
