package teo

import (
	"context"
	"fmt"
	"log"
	"strings"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	teov20220901 "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/teo/v20220901"

	tccommon "github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/common"
	"github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/internal/helper"
)

// ResourceTencentCloudTeoExportZoneConfig returns a resource definition for exporting TEO zone configuration.
// This resource allows users to export TEO (TencentCloud Edge One) zone configurations.
func ResourceTencentCloudTeoExportZoneConfig() *schema.Resource {
	return &schema.Resource{
		Create: resourceTencentCloudTeoExportZoneConfigCreate,
		Read:   resourceTencentCloudTeoExportZoneConfigRead,
		Update: resourceTencentCloudTeoExportZoneConfigUpdate,
		Delete: resourceTencentCloudTeoExportZoneConfigDelete,
		Importer: &schema.ResourceImporter{
			State: schema.ImportStatePassthrough,
		},
		Timeouts: &schema.ResourceTimeout{
			Create: schema.DefaultTimeout(tccommon.DefaultTimeout),
			Read:   schema.DefaultTimeout(tccommon.DefaultTimeout),
			Update: schema.DefaultTimeout(tccommon.DefaultTimeout),
			Delete: schema.DefaultTimeout(tccommon.DefaultTimeout),
		},
		Schema: map[string]*schema.Schema{
			"zone_id": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: "Zone ID.",
			},

			"types": {
				Type:        schema.TypeList,
				Optional:    true,
				Description: "List of types to export. If not specified, all types will be exported. Current supported values include: <li>L7AccelerationConfig: Export L7 acceleration configuration, corresponding to \"Site Acceleration - Global Acceleration Configuration\" and \"Site Acceleration - Rule Engine\" in the console.</li>",
				Elem: &schema.Schema{
					Type: schema.TypeString,
				},
			},

			"content": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The specific content of the exported configuration. Returned in JSON format, encoded in UTF-8.",
			},

			"request_id": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The unique request ID, generated by the server.",
			},
		},
	}
}

func resourceTencentCloudTeoExportZoneConfigCreate(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_teo_export_zone_config.create")()
	defer tccommon.InconsistentCheck(d, meta)()

	var (
		logId   = tccommon.GetLogId(tccommon.ContextNil)
		ctx     = tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)
		zoneId  = d.Get("zone_id").(string)
		request = teov20220901.NewExportZoneConfigRequest()
	)

	request.ZoneId = helper.String(zoneId)

	if v, ok := d.GetOk("types"); ok {
		for _, item := range v.([]interface{}) {
			request.Types = append(request.Types, helper.String(item.(string)))
		}
	}

	response := teov20220901.NewExportZoneConfigResponse()
	reqErr := resource.Retry(tccommon.WriteRetryTimeout, func() *resource.RetryError {
		result, e := meta.(tccommon.ProviderMeta).GetAPIV3Conn().UseTeoV20220901Client().ExportZoneConfigWithContext(ctx, request)
		if e != nil {
			return tccommon.RetryError(e)
		} else {
			log.Printf("[DEBUG]%s api[%s] success, request body [%s], response body [%s]\n", logId, request.GetAction(), request.ToJsonString(), result.ToJsonString())
		}

		if result == nil || result.Response == nil {
			return resource.NonRetryableError(strings.NewReplacer("\n", "").Replace(fmt.Sprintf("Export teo zone config failed, Response is nil.")))
		}

		response = result
		return nil
	})

	if reqErr != nil {
		log.Printf("[CRITAL]%s export teo zone config failed, reason:%+v", logId, reqErr)
		return reqErr
	}

	d.SetId(zoneId)
	return resourceTencentCloudTeoExportZoneConfigRead(d, meta)
}

func resourceTencentCloudTeoExportZoneConfigRead(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_teo_export_zone_config.read")()
	defer tccommon.InconsistentCheck(d, meta)()

	var (
		logId   = tccommon.GetLogId(tccommon.ContextNil)
		ctx     = tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)
		zoneId  = d.Id()
		request = teov20220901.NewExportZoneConfigRequest()
	)

	request.ZoneId = helper.String(zoneId)

	if v, ok := d.GetOk("types"); ok {
		for _, item := range v.([]interface{}) {
			request.Types = append(request.Types, helper.String(item.(string)))
		}
	}

	response := teov20220901.NewExportZoneConfigResponse()
	err := resource.Retry(tccommon.ReadRetryTimeout, func() *resource.RetryError {
		result, e := meta.(tccommon.ProviderMeta).GetAPIV3Conn().UseTeoV20220901Client().ExportZoneConfigWithContext(ctx, request)
		if e != nil {
			return tccommon.RetryError(e)
		} else {
			log.Printf("[DEBUG]%s api[%s] success, request body [%s], response body [%s]\n", logId, request.GetAction(), request.ToJsonString(), result.ToJsonString())
		}

		if result == nil || result.Response == nil {
			return resource.NonRetryableError(strings.NewReplacer("\n", "").Replace(fmt.Sprintf("Export teo zone config failed, Response is nil.")))
		}

		response = result
		return nil
	})

	if err != nil {
		log.Printf("[WARN]%s read teo zone config failed, reason:%+v", logId, err)
		return err
	}

	_ = d.Set("zone_id", zoneId)

	if response.Response.Content != nil {
		_ = d.Set("content", response.Response.Content)
	}

	if response.Response.RequestId != nil {
		_ = d.Set("request_id", response.Response.RequestId)
	}

	return nil
}

func resourceTencentCloudTeoExportZoneConfigUpdate(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_teo_export_zone_config.update")()
	defer tccommon.InconsistentCheck(d, meta)()

	var (
		logId   = tccommon.GetLogId(tccommon.ContextNil)
		ctx     = tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)
		zoneId  = d.Id()
		request = teov20220901.NewExportZoneConfigRequest()
	)

	request.ZoneId = helper.String(zoneId)

	if v, ok := d.GetOk("types"); ok {
		for _, item := range v.([]interface{}) {
			request.Types = append(request.Types, helper.String(item.(string)))
		}
	}

	response := teov20220901.NewExportZoneConfigResponse()
	reqErr := resource.Retry(tccommon.WriteRetryTimeout, func() *resource.RetryError {
		result, e := meta.(tccommon.ProviderMeta).GetAPIV3Conn().UseTeoV20220901Client().ExportZoneConfigWithContext(ctx, request)
		if e != nil {
			return tccommon.RetryError(e)
		} else {
			log.Printf("[DEBUG]%s api[%s] success, request body [%s], response body [%s]\n", logId, request.GetAction(), request.ToJsonString(), result.ToJsonString())
		}

		if result == nil || result.Response == nil {
			return resource.NonRetryableError(strings.NewReplacer("\n", "").Replace(fmt.Sprintf("Export teo zone config failed, Response is nil.")))
		}

		response = result
		return nil
	})

	if reqErr != nil {
		log.Printf("[CRITAL]%s export teo zone config failed, reason:%+v", logId, reqErr)
		return reqErr
	}

	return resourceTencentCloudTeoExportZoneConfigRead(d, meta)
}

func resourceTencentCloudTeoExportZoneConfigDelete(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_teo_export_zone_config.delete")()
	defer tccommon.InconsistentCheck(d, meta)()

	log.Printf("[INFO]%s resource `teo_export_zone_config` [%s] deleted, this only removes the Terraform state and does not affect the actual TEO zone configuration.\n",
		tccommon.GetLogId(tccommon.ContextNil), d.Id())

	return nil
}
