// Code generated by iacg; DO NOT EDIT.
package teo

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"log"
	"strings"
	"text/template"
	"time"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	teov20220901 "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/teo/v20220901"

	tccommon "github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/common"
	"github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/internal/helper"
)

func ResourceTencentCloudTeoFunction() *schema.Resource {
	return &schema.Resource{
		Create: resourceTencentCloudTeoFunctionCreate,
		Read:   resourceTencentCloudTeoFunctionRead,
		Update: resourceTencentCloudTeoFunctionUpdate,
		Delete: resourceTencentCloudTeoFunctionDelete,
		Importer: &schema.ResourceImporter{
			State: schema.ImportStatePassthrough,
		},
		Schema: map[string]*schema.Schema{
			"zone_id": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: "ID of the site.",
			},

			"function_id": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "ID of the Function.",
			},

			"name": {
				Type:        schema.TypeString,
				Required:    true,
				Description: "Function name. It can only contain lowercase letters, numbers, hyphens, must start and end with a letter or number, and can have a maximum length of 30 characters.",
			},

			"remark": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "Function description, maximum support of 60 characters.",
			},

			"content": {
				Type:        schema.TypeString,
				Required:    true,
				Description: "Function content, currently only supports JavaScript code, with a maximum size of 5MB.",
			},

			"domain": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The default domain name for the function.",
			},

			"create_time": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "Creation time. The time is in Coordinated Universal Time (UTC) and follows the date and time format specified by the ISO 8601 standard.",
			},

			"update_time": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "Modification time. The time is in Coordinated Universal Time (UTC) and follows the date and time format specified by the ISO 8601 standard.",
			},

			"environment_variables": {
				Type:        schema.TypeList,
				Optional:    true,
				Computed:    true,
				Description: "The environment variable list for the function.",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"key": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "The name of the variable, which is limited to alphanumeric characters and the special characters `@`, `.`, `-`, and `_`. It can have a maximum of 64 bytes and should not be duplicated.",
						},
						"value": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "The value of the variable, which is limited to a maximum of 5000 bytes. The default value is empty.",
						},
						"type": {
							Type:        schema.TypeString,
							Optional:    true,
							Default:     "string",
							Description: "The type of the variable can have the following values:  - `string`: Represents a string type.  - `json`: Represents a JSON object type.",
						},
					},
				},
			},

			"rules": {
				Type:        schema.TypeList,
				Optional:    true,
				Computed:    true,
				Description: "The function rule list for the function.",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"rule_id": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "ID of the Function Rule.",
						},
						"remark": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "Rule description, maximum support of 60 characters.",
						},
						"priority": {
							Type:        schema.TypeInt,
							Computed:    true,
							Description: "The priority of function trigger rule. A higher numerical value indicates a higher priority.",
						},
						"function_rule_conditions": {
							Type:        schema.TypeList,
							Required:    true,
							Description: "The list of rule conditions, where conditions are connected by an \"OR\" relationship.",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"rule_conditions": {
										Type:        schema.TypeList,
										Required:    true,
										Description: "For edge function trigger rule conditions, if all items in list are satisfied, then condition is considered fulfilled.",
										Elem: &schema.Resource{
											Schema: map[string]*schema.Schema{
												"operator": {
													Type:        schema.TypeString,
													Required:    true,
													Description: "Operator. Valid values:\n  - `equals`: Equals.\n  - `notEquals`: Does not equal.\n  - `exist`: Exists.\n  - `notexist`: Does not exist.",
												},
												"target": {
													Type:        schema.TypeString,
													Required:    true,
													Description: "The match type. Values:\n  - `filename`: File name.\n  - `extension`: File extension.\n  - `host`: Host.\n  - `full_url`: Full URL, which indicates to complete URL path under current site and must contain HTTP protocol, host, and path.\n  - `url`: Partial URL under current site.\n  - `client_country`: Country/Region of client.\n  - `query_string`: Query string in request URL.\n  - `request_header`: HTTP request header.",
												},
												"values": {
													Type:        schema.TypeSet,
													Optional:    true,
													Description: "The parameter value of match type.",
													Elem: &schema.Schema{
														Type: schema.TypeString,
													},
												},
												"ignore_case": {
													Type:        schema.TypeBool,
													Optional:    true,
													Description: "Whether parameter value is case insensitive. Default value: false.",
												},
												"name": {
													Type:        schema.TypeString,
													Optional:    true,
													Description: "The parameter name of match type. This field is required only when `Target=query_string/request_header`.",
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},

			"region_selection": {
				Type:        schema.TypeList,
				Optional:    true,
				Computed:    true,
				Description: "The region selection configuration for the function deployment. If not specified, the function is deployed globally.",
				Elem: &schema.Schema{
					Type: schema.TypeString,
				},
			},
		},
	}
}

func resourceTencentCloudTeoFunctionCreate(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_teo_function.create")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)

	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	var (
		zoneId     string
		functionId string
	)
	var (
		request  = teov20220901.NewCreateFunctionRequest()
		response = teov20220901.NewCreateFunctionResponse()
	)

	if v, ok := d.GetOk("zone_id"); ok {
		zoneId = v.(string)
	}

	request.ZoneId = helper.String(zoneId)

	if v, ok := d.GetOk("name"); ok {
		request.Name = helper.String(v.(string))
	}

	if v, ok := d.GetOk("remark"); ok {
		request.Remark = helper.String(v.(string))
	}

	if v, ok := d.GetOk("content"); ok {
		request.Content = helper.String(v.(string))
	}

	err := resource.Retry(tccommon.WriteRetryTimeout, func() *resource.RetryError {
		result, e := meta.(tccommon.ProviderMeta).GetAPIV3Conn().UseTeoV20220901Client().CreateFunctionWithContext(ctx, request)
		if e != nil {
			return tccommon.RetryError(e)
		} else {
			log.Printf("[DEBUG]%s api[%s] success, request body [%s], response body [%s]\n", logId, request.GetAction(), request.ToJsonString(), result.ToJsonString())
		}
		response = result
		return nil
	})
	if err != nil {
		log.Printf("[CRITAL]%s create teo function failed, reason:%+v", logId, err)
		return err
	}

	functionId = *response.Response.FunctionId

	if _, err := (&resource.StateChangeConf{
		Delay:      10 * time.Second,
		MinTimeout: 3 * time.Second,
		Pending:    []string{"false"},
		Refresh:    resourceTeoFunctionCreateStateRefreshFunc_0_0(ctx, zoneId, functionId),
		Target:     []string{"true"},
		Timeout:    600 * time.Second,
	}).WaitForStateContext(ctx); err != nil {
		return err
	}
	d.SetId(strings.Join([]string{zoneId, functionId}, tccommon.FILED_SP))

	// Handle environment variables after function creation
	if v, ok := d.GetOk("environment_variables"); ok && len(v.([]interface{})) > 0 {
		if err := handleTeoFunctionEnvironmentVariables(ctx, d, meta, zoneId, functionId, "setEnvironmentVariable"); err != nil {
			return err
		}
	}

	// Handle rules after function creation
	if v, ok := d.GetOk("rules"); ok && len(v.([]interface{})) > 0 {
		if err := handleTeoFunctionRules(ctx, d, meta, zoneId, functionId); err != nil {
			return err
		}
	}

	return resourceTencentCloudTeoFunctionRead(d, meta)
}

func resourceTencentCloudTeoFunctionRead(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_teo_function.read")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)

	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	service := TeoService{client: meta.(tccommon.ProviderMeta).GetAPIV3Conn()}

	idSplit := strings.Split(d.Id(), tccommon.FILED_SP)
	if len(idSplit) != 2 {
		return fmt.Errorf("id is broken,%s", d.Id())
	}
	zoneId := idSplit[0]
	functionId := idSplit[1]

	_ = d.Set("zone_id", zoneId)

	respData, err := service.DescribeTeoFunctionById(ctx, zoneId, functionId)
	if err != nil {
		return err
	}

	if respData == nil {
		d.SetId("")
		log.Printf("[WARN]%s resource `teo_function` [%s] not found, please check if it has been deleted.\n", logId, d.Id())
		return nil
	}
	if respData.FunctionId != nil {
		_ = d.Set("function_id", respData.FunctionId)
		functionId = *respData.FunctionId
	}

	if respData.Name != nil {
		_ = d.Set("name", respData.Name)
	}

	if respData.Remark != nil {
		_ = d.Set("remark", respData.Remark)
	}

	if respData.Content != nil {
		_ = d.Set("content", respData.Content)
	}

	if respData.Domain != nil {
		_ = d.Set("domain", respData.Domain)
	}

	if respData.CreateTime != nil {
		_ = d.Set("create_time", respData.CreateTime)
	}

	if respData.UpdateTime != nil {
		_ = d.Set("update_time", respData.UpdateTime)
	}

	// Read environment variables
	envService := TeoService{client: meta.(tccommon.ProviderMeta).GetAPIV3Conn()}
	envData, err := envService.DescribeTeoFunctionRuntimeEnvironmentById(ctx, zoneId, functionId)
	if err == nil && envData != nil && len(envData.EnvironmentVariables) > 0 {
		environmentVariablesList := make([]map[string]interface{}, 0, len(envData.EnvironmentVariables))
		for _, environmentVariables := range envData.EnvironmentVariables {
			environmentVariablesMap := map[string]interface{}{}

			if environmentVariables.Key != nil {
				environmentVariablesMap["key"] = environmentVariables.Key
			}

			if environmentVariables.Value != nil {
				environmentVariablesMap["value"] = environmentVariables.Value
			}

			if environmentVariables.Type != nil {
				environmentVariablesMap["type"] = environmentVariables.Type
			}

			environmentVariablesList = append(environmentVariablesList, environmentVariablesMap)
		}

		_ = d.Set("environment_variables", environmentVariablesList)
	}

	// Read rules
	ruleData, err := envService.DescribeTeoFunctionRulesByFunctionId(ctx, zoneId, functionId)
	if err == nil && ruleData != nil && len(ruleData.FunctionRules) > 0 {
		rulesList := make([]map[string]interface{}, 0, len(ruleData.FunctionRules))
		for _, rule := range ruleData.FunctionRules {
			ruleMap := map[string]interface{}{}

			if rule.RuleId != nil {
				ruleMap["rule_id"] = rule.RuleId
			}

			if rule.Remark != nil {
				ruleMap["remark"] = rule.Remark
			}

			if rule.Priority != nil {
				ruleMap["priority"] = rule.Priority
			}

			if rule.FunctionRuleConditions != nil {
				functionRuleConditionsList := make([]map[string]interface{}, 0, len(rule.FunctionRuleConditions))
				for _, functionRuleCondition := range rule.FunctionRuleConditions {
					functionRuleConditionMap := map[string]interface{}{}

					if functionRuleCondition.RuleConditions != nil {
						ruleConditionsList := make([]map[string]interface{}, 0, len(functionRuleCondition.RuleConditions))
						for _, ruleCondition := range functionRuleCondition.RuleConditions {
							ruleConditionMap := map[string]interface{}{}

							if ruleCondition.Operator != nil {
								ruleConditionMap["operator"] = ruleCondition.Operator
							}

							if ruleCondition.Target != nil {
								ruleConditionMap["target"] = ruleCondition.Target
							}

							if ruleCondition.Values != nil {
								valuesSet := schema.NewSet(schema.HashString, []interface{}{})
								for _, val := range ruleCondition.Values {
									valuesSet.Add(*val)
								}
								ruleConditionMap["values"] = valuesSet
							}

							if ruleCondition.IgnoreCase != nil {
								ruleConditionMap["ignore_case"] = ruleCondition.IgnoreCase
							}

							if ruleCondition.Name != nil {
								ruleConditionMap["name"] = ruleCondition.Name
							}

							ruleConditionsList = append(ruleConditionsList, ruleConditionMap)
						}
						functionRuleConditionMap["rule_conditions"] = ruleConditionsList
					}

					functionRuleConditionsList = append(functionRuleConditionsList, functionRuleConditionMap)
				}
				ruleMap["function_rule_conditions"] = functionRuleConditionsList
			}

			rulesList = append(rulesList, ruleMap)
		}

		_ = d.Set("rules", rulesList)
	}

	return nil
}

func resourceTencentCloudTeoFunctionUpdate(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_teo_function.update")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)

	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	immutableArgs := []string{"name"}
	for _, v := range immutableArgs {
		if d.HasChange(v) {
			return fmt.Errorf("argument `%s` cannot be changed", v)
		}
	}
	idSplit := strings.Split(d.Id(), tccommon.FILED_SP)
	if len(idSplit) != 2 {
		return fmt.Errorf("id is broken,%s", d.Id())
	}
	zoneId := idSplit[0]
	functionId := idSplit[1]

	needChange := false
	mutableArgs := []string{"remark", "content", "environment_variables", "rules"}
	for _, v := range mutableArgs {
		if d.HasChange(v) {
			needChange = true
			break
		}
	}

	if needChange {
		request := teov20220901.NewModifyFunctionRequest()

		request.ZoneId = helper.String(zoneId)

		request.FunctionId = helper.String(functionId)

		if v, ok := d.GetOk("remark"); ok {
			request.Remark = helper.String(v.(string))
		}

		if v, ok := d.GetOk("content"); ok {
			request.Content = helper.String(v.(string))
		}

		if d.HasChange("remark") || d.HasChange("content") {
			err := resource.Retry(tccommon.WriteRetryTimeout, func() *resource.RetryError {
				result, e := meta.(tccommon.ProviderMeta).GetAPIV3Conn().UseTeoV20220901Client().ModifyFunctionWithContext(ctx, request)
				if e != nil {
					return tccommon.RetryError(e)
				} else {
					log.Printf("[DEBUG]%s api[%s] success, request body [%s], response body [%s]\n", logId, request.GetAction(), request.ToJsonString(), result.ToJsonString())
				}
				return nil
			})
			if err != nil {
				log.Printf("[CRITAL]%s update teo function failed, reason:%+v", logId, err)
				return err
			}
		}

		// Handle environment variables update
		if d.HasChange("environment_variables") {
			_, new := d.GetChange("environment_variables")
			if len(new.([]interface{})) == 0 {
				// Clear all environment variables
				if err := handleTeoFunctionEnvironmentVariables(ctx, d, meta, zoneId, functionId, "clearEnvironmentVariable"); err != nil {
					return err
				}
			} else {
				// Set or reset environment variables
				if err := handleTeoFunctionEnvironmentVariables(ctx, d, meta, zoneId, functionId, "resetEnvironmentVariable"); err != nil {
					return err
				}
			}
		}

		// Handle rules update
		if d.HasChange("rules") {
			old, new := d.GetChange("rules")
			oldRules := old.([]interface{})
			newRules := new.([]interface{})

			// Delete old rules
			for _, oldRule := range oldRules {
				oldRuleMap := oldRule.(map[string]interface{})
				if ruleId, ok := oldRuleMap["rule_id"].(string); ok && ruleId != "" {
					if err := deleteTeoFunctionRule(ctx, d, meta, zoneId, ruleId); err != nil {
						return err
					}
				}
			}

			// Create new rules
			if len(newRules) > 0 {
				if err := handleTeoFunctionRules(ctx, d, meta, zoneId, functionId); err != nil {
					return err
				}
			}
		}
	}

	return resourceTencentCloudTeoFunctionRead(d, meta)
}

func resourceTencentCloudTeoFunctionDelete(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_teo_function.delete")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)
	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	idSplit := strings.Split(d.Id(), tccommon.FILED_SP)
	if len(idSplit) != 2 {
		return fmt.Errorf("id is broken,%s", d.Id())
	}
	zoneId := idSplit[0]
	functionId := idSplit[1]

	var (
		request  = teov20220901.NewDeleteFunctionRequest()
		response = teov20220901.NewDeleteFunctionResponse()
	)

	request.ZoneId = helper.String(zoneId)

	request.FunctionId = helper.String(functionId)

	err := resource.Retry(tccommon.WriteRetryTimeout, func() *resource.RetryError {
		result, e := meta.(tccommon.ProviderMeta).GetAPIV3Conn().UseTeoV20220901Client().DeleteFunctionWithContext(ctx, request)
		if e != nil {
			return tccommon.RetryError(e)
		} else {
			log.Printf("[DEBUG]%s api[%s] success, request body [%s], response body [%s]\n", logId, request.GetAction(), request.ToJsonString(), result.ToJsonString())
		}
		response = result
		return nil
	})
	if err != nil {
		log.Printf("[CRITAL]%s delete teo function failed, reason:%+v", logId, err)
		return err
	}

	_ = response
	return nil
}

func resourceTeoFunctionCreateStateRefreshFunc_0_0(ctx context.Context, zoneId string, functionId string) resource.StateRefreshFunc {
	var req *teov20220901.DescribeFunctionsRequest
	t := template.New("gotpl")
	var tplObj *template.Template
	return func() (interface{}, string, error) {
		meta := tccommon.ProviderMetaFromContext(ctx)
		if meta == nil {
			return nil, "", fmt.Errorf("resource data can not be nil")
		}
		if req == nil {
			d := tccommon.ResourceDataFromContext(ctx)
			if d == nil {
				return nil, "", fmt.Errorf("resource data can not be nil")
			}
			_ = d
			req = teov20220901.NewDescribeFunctionsRequest()
			req.ZoneId = helper.String(zoneId)

			req.FunctionIds = []*string{helper.String(functionId)}

		}
		resp, err := meta.(tccommon.ProviderMeta).GetAPIV3Conn().UseTeoV20220901Client().DescribeFunctionsWithContext(ctx, req)
		if err != nil {
			return nil, "", err
		}
		if resp == nil || resp.Response == nil {
			return nil, "", nil
		}
		if tplObj == nil {
			tplObj, err = t.Parse("{{ if .Functions }}{{ $firstFunction := index .Functions 0 }}{{ if $firstFunction.Domain }}{{ true }}{{ else }}{{ false }}{{ end }}{{ end }}")
			if err != nil {
				return resp.Response, "", fmt.Errorf("parse state go-template error: %w", err)
			}
		}
		stream := new(bytes.Buffer)
		if err := tplObj.Execute(stream, resp.Response); err != nil {
			return resp.Response, "", err
		}
		stateBytes, err := io.ReadAll(stream)
		if err != nil {
			return resp.Response, "", err
		}
		state := string(stateBytes)
		return resp.Response, state, nil
	}
}

// handleTeoFunctionEnvironmentVariables handles environment variables for a function
func handleTeoFunctionEnvironmentVariables(ctx context.Context, d *schema.ResourceData, meta interface{}, zoneId string, functionId string, operation string) error {
	logId := tccommon.GetLogId(ctx)

	request := teov20220901.NewHandleFunctionRuntimeEnvironmentRequest()
	request.ZoneId = helper.String(zoneId)
	request.FunctionId = helper.String(functionId)
	request.Operation = helper.String(operation)

	if v, ok := d.GetOk("environment_variables"); ok {
		for _, item := range v.([]interface{}) {
			environmentVariablesMap := item.(map[string]interface{})
			functionEnvironmentVariable := teov20220901.FunctionEnvironmentVariable{}
			if v, ok := environmentVariablesMap["key"]; ok {
				functionEnvironmentVariable.Key = helper.String(v.(string))
			}
			if v, ok := environmentVariablesMap["value"]; ok {
				functionEnvironmentVariable.Value = helper.String(v.(string))
			}
			if v, ok := environmentVariablesMap["type"]; ok {
				functionEnvironmentVariable.Type = helper.String(v.(string))
			}
			request.EnvironmentVariables = append(request.EnvironmentVariables, &functionEnvironmentVariable)
		}
	}

	err := resource.Retry(tccommon.WriteRetryTimeout, func() *resource.RetryError {
		result, e := meta.(tccommon.ProviderMeta).GetAPIV3Conn().UseTeoV20220901Client().HandleFunctionRuntimeEnvironmentWithContext(ctx, request)
		if e != nil {
			return tccommon.RetryError(e)
		} else {
			log.Printf("[DEBUG]%s api[%s] success, request body [%s], response body [%s]\n", logId, request.GetAction(), request.ToJsonString(), result.ToJsonString())
		}
		return nil
	})
	if err != nil {
		log.Printf("[CRITAL]%s handle teo function environment variables failed, reason:%+v", logId, err)
		return err
	}

	return nil
}

// handleTeoFunctionRules handles rules for a function
func handleTeoFunctionRules(ctx context.Context, d *schema.ResourceData, meta interface{}, zoneId string, functionId string) error {
	logId := tccommon.GetLogId(ctx)

	if v, ok := d.GetOk("rules"); ok {
		for _, item := range v.([]interface{}) {
			ruleMap := item.(map[string]interface{})

			request := teov20220901.NewCreateFunctionRuleRequest()
			request.ZoneId = helper.String(zoneId)
			request.FunctionId = helper.String(functionId)

			if v, ok := ruleMap["remark"]; ok && v.(string) != "" {
				request.Remark = helper.String(v.(string))
			}

			if v, ok := ruleMap["function_rule_conditions"]; ok {
				for _, item := range v.([]interface{}) {
					functionRuleConditionsMap := item.(map[string]interface{})
					functionRuleCondition := teov20220901.FunctionRuleCondition{}
					if v, ok := functionRuleConditionsMap["rule_conditions"]; ok {
						for _, item := range v.([]interface{}) {
							ruleConditionsMap := item.(map[string]interface{})
							ruleCondition := teov20220901.RuleCondition{}
							if v, ok := ruleConditionsMap["operator"]; ok {
								ruleCondition.Operator = helper.String(v.(string))
							}
							if v, ok := ruleConditionsMap["target"]; ok {
								ruleCondition.Target = helper.String(v.(string))
							}
							if v, ok := ruleConditionsMap["values"]; ok {
								valuesSet := v.(*schema.Set).List()
								for i := range valuesSet {
									values := valuesSet[i].(string)
									ruleCondition.Values = append(ruleCondition.Values, helper.String(values))
								}
							}
							if v, ok := ruleConditionsMap["ignore_case"]; ok {
								ruleCondition.IgnoreCase = helper.Bool(v.(bool))
							}
							if v, ok := ruleConditionsMap["name"]; ok {
								ruleCondition.Name = helper.String(v.(string))
							}
							functionRuleCondition.RuleConditions = append(functionRuleCondition.RuleConditions, &ruleCondition)
						}
					}
					request.FunctionRuleConditions = append(request.FunctionRuleConditions, &functionRuleCondition)
				}
			}

			err := resource.Retry(tccommon.WriteRetryTimeout, func() *resource.RetryError {
				result, e := meta.(tccommon.ProviderMeta).GetAPIV3Conn().UseTeoV20220901Client().CreateFunctionRuleWithContext(ctx, request)
				if e != nil {
					return tccommon.RetryError(e)
				} else {
					log.Printf("[DEBUG]%s api[%s] success, request body [%s], response body [%s]\n", logId, request.GetAction(), request.ToJsonString(), result.ToJsonString())
				}
				return nil
			})
			if err != nil {
				log.Printf("[CRITAL]%s create teo function rule failed, reason:%+v", logId, err)
				return err
			}
		}
	}

	return nil
}

// deleteTeoFunctionRule deletes a function rule
func deleteTeoFunctionRule(ctx context.Context, d *schema.ResourceData, meta interface{}, zoneId string, ruleId string) error {
	logId := tccommon.GetLogId(ctx)

	request := teov20220901.NewDeleteFunctionRulesRequest()
	request.ZoneId = helper.String(zoneId)
	request.RuleIds = []*string{helper.String(ruleId)}

	err := resource.Retry(tccommon.WriteRetryTimeout, func() *resource.RetryError {
		result, e := meta.(tccommon.ProviderMeta).GetAPIV3Conn().UseTeoV20220901Client().DeleteFunctionRulesWithContext(ctx, request)
		if e != nil {
			return tccommon.RetryError(e)
		} else {
			log.Printf("[DEBUG]%s api[%s] success, request body [%s], response body [%s]\n", logId, request.GetAction(), request.ToJsonString(), result.ToJsonString())
		}
		return nil
	})
	if err != nil {
		log.Printf("[CRITAL]%s delete teo function rule failed, reason:%+v", logId, err)
		return err
	}

	return nil
}

