// Code generated by iacg; DO NOT EDIT.
package teo

import (
	"context"
	"fmt"
	"log"
	"strings"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	teov20220901 "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/teo/v20220901"
	tccommon "github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/common"
	"github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/internal/helper"
)

func ResourceTencentCloudTeoConfigGroupVersion() *schema.Resource {
	return &schema.Resource{
		Create: resourceTencentCloudTeoConfigGroupVersionCreate,
		Read:   resourceTencentCloudTeoConfigGroupVersionRead,
		Delete: resourceTencentCloudTeoConfigGroupVersionDelete,
		Importer: &schema.ResourceImporter{
			State: schema.ImportStatePassthrough,
		},
		Schema: map[string]*schema.Schema{
			"zone_id": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: "Zone ID.",
			},

			"group_id": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: "GroupId of the version to be created.",
			},

			"description": {
				Type:        schema.TypeString,
				Optional:    true,
				ForceNew:    true,
				Description: "Version description. The maximum length allowed is 50 characters. This field can be used to provide details about the application scenarios of this version.",
			},

			"content": {
				Type:             schema.TypeString,
				Required:         true,
				ForceNew:         true,
				Description:      "Configuration content to be imported. It is required to be in JSON format and encoded in UTF-8. Please refer to the example below for the configuration file content.",
				DiffSuppressFunc: helper.DiffSupressJSON,
			},

			"version_id": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "Version ID.",
			},

			"version_number": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "Version number.",
			},

			"group_type": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "Configuration group type. Valid values: l7_acceleration (Layer 7 acceleration configuration group), edge_functions (Edge function configuration group).",
			},

			"status": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "Version status. Valid values: creating (Creating), inactive (Inactive), active (Active).",
			},

			"create_time": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "Version creation time. The time follows the ISO 8601 standard in the date and time format.",
			},
		},
	}
}

func resourceTencentCloudTeoConfigGroupVersionCreate(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_teo_config_group_version.create")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)

	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	var (
		zoneId    string
		groupId   string
		versionId string
	)
	var (
		request  = teov20220901.NewCreateConfigGroupVersionRequest()
		response = teov20220901.NewCreateConfigGroupVersionResponse()
	)

	if v, ok := d.GetOk("zone_id"); ok {
		zoneId = v.(string)
		request.ZoneId = helper.String(v.(string))
	}

	if v, ok := d.GetOk("group_id"); ok {
		groupId = v.(string)
		request.GroupId = helper.String(v.(string))
	}

	if v, ok := d.GetOk("description"); ok {
		request.Description = helper.String(v.(string))
	}

	if v, ok := d.GetOk("content"); ok {
		request.Content = helper.String(v.(string))
	}

	reqErr := resource.Retry(tccommon.WriteRetryTimeout, func() *resource.RetryError {
		result, e := meta.(tccommon.ProviderMeta).GetAPIV3Conn().UseTeoV20220901Client().CreateConfigGroupVersionWithContext(ctx, request)
		if e != nil {
			return tccommon.RetryError(e)
		} else {
			log.Printf("[DEBUG]%s api[%s] success, request body [%s], response body [%s]\n", logId, request.GetAction(), request.ToJsonString(), result.ToJsonString())
		}
		response = result
		return nil
	})
	if reqErr != nil {
		log.Printf("[CRITAL]%s create teo config group version failed, reason:%+v", logId, reqErr)
		return reqErr
	}

	if response.Response.VersionId != nil {
		versionId = *response.Response.VersionId
	}

	d.SetId(strings.Join([]string{zoneId, groupId, versionId}, tccommon.FILED_SP))

	return resourceTencentCloudTeoConfigGroupVersionRead(d, meta)
}

func resourceTencentCloudTeoConfigGroupVersionRead(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_teo_config_group_version.read")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)

	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	service := TeoService{client: meta.(tccommon.ProviderMeta).GetAPIV3Conn()}

	idSplit := strings.Split(d.Id(), tccommon.FILED_SP)
	if len(idSplit) != 3 {
		return fmt.Errorf("id is broken,%s", d.Id())
	}
	zoneId := idSplit[0]
	groupId := idSplit[1]
	versionId := idSplit[2]

	respData, err := service.DescribeTeoConfigGroupVersionById(ctx, zoneId, groupId, versionId)
	if err != nil {
		return err
	}

	if respData == nil {
		d.SetId("")
		log.Printf("[WARN]%s resource `teo_config_group_version` [%s] not found, please check if it has been deleted.\n", logId, d.Id())
		return nil
	}

	if respData.ConfigGroupVersionInfo != nil {
		if respData.ConfigGroupVersionInfo.VersionId != nil {
			_ = d.Set("version_id", respData.ConfigGroupVersionInfo.VersionId)
		}

		if respData.ConfigGroupVersionInfo.VersionNumber != nil {
			_ = d.Set("version_number", respData.ConfigGroupVersionInfo.VersionNumber)
		}

		if respData.ConfigGroupVersionInfo.GroupId != nil {
			_ = d.Set("group_id", respData.ConfigGroupVersionInfo.GroupId)
		}

		if respData.ConfigGroupVersionInfo.GroupType != nil {
			_ = d.Set("group_type", respData.ConfigGroupVersionInfo.GroupType)
		}

		if respData.ConfigGroupVersionInfo.Description != nil {
			_ = d.Set("description", respData.ConfigGroupVersionInfo.Description)
		}

		if respData.ConfigGroupVersionInfo.Status != nil {
			_ = d.Set("status", respData.ConfigGroupVersionInfo.Status)
		}

		if respData.ConfigGroupVersionInfo.CreateTime != nil {
			_ = d.Set("create_time", respData.ConfigGroupVersionInfo.CreateTime)
		}
	}

	if respData.Content != nil {
		_ = d.Set("content", respData.Content)
	}

	_ = d.Set("zone_id", zoneId)

	return nil
}

func resourceTencentCloudTeoConfigGroupVersionDelete(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_teo_config_group_version.delete")()
	defer tccommon.InconsistentCheck(d, meta)()

	return nil
}
