package tencentcloud

const (
	WORKFLOW_STATUS_ENABLED  = "Enabled"
	WORKFLOW_STATUS_DISABLED = "Disabled"
)

const (
	PROTOCOL_RTP       = "RTP"
	PROTOCOL_SRT       = "SRT"
	PROTOCOL_RTMP      = "RTMP"
	PROTOCOL_HLS       = "HLS"
	PROTOCOL_RTMP_PULL = "RTMP_PULL"
	PROTOCOL_RTSP_PULL = "RTSP_PULL"
	PROTOCOL_HLS_PULL  = "HLS_PULL"
)
