package tencentcloud

const (
	DDOS_EIP_BIND_STATUS_BINDING   = "BINDING"
	DDOS_EIP_BIND_STATUS_BIND      = "BIND"
	DDOS_EIP_BIND_STATUS_UNBINDING = "UNBINDING"
	DDOS_EIP_BIND_STATUS_UNBIND    = "UNBIND"
)

var DDOS_EIP_BIND_STATUS = []string{DDOS_EIP_BIND_STATUS_BINDING, DDOS_EIP_BIND_STATUS_BIND, DDOS_EIP_BIND_STATUS_UNBINDING, DDOS_EIP_BIND_STATUS_UNBIND}

const (
	DDOS_EIP_BIND_RESOURCE_TYPE_CVM = "cvm"
	DDOS_EIP_BIND_RESOURCE_TYPE_CLB = "clb"
	s
)

var DDOS_EIP_BIND_RESOURCE_TYPE = []string{DDOS_EIP_BIND_RESOURCE_TYPE_CVM, DDOS_EIP_BIND_RESOURCE_TYPE_CLB}
