package tencentcloud

const (
	CDWCH_PAY_MODE_HOUR   = "hour"
	CDWCH_PAY_MODE_PREPAY = "prepay"
)

const (
	CDWCH_CHARGE_TYPE_PREPAID          = "PREPAID"
	CDWCH_CHARGE_TYPE_POSTPAID_BY_HOUR = "POSTPAID_BY_HOUR"
)

const (
	NODE_TYPE_CLICKHOUSE = "DATA"
	NODE_TYPE_ZOOKEEPER  = "COMMON"
)

const (
	OPERATION_TYPE_CREATE = "create"
	OPERATION_TYPE_UPDATE = "update"
)

const (
	SCHEDULE_TYPE_DATA = "data"
	SCHEDULE_TYPE_META = "meta"
)

var PAY_MODE_TO_CHARGE_TYPE = map[string]string{
	CDWCH_PAY_MODE_HOUR:   CDWCH_CHARGE_TYPE_POSTPAID_BY_HOUR,
	CDWCH_PAY_MODE_PREPAY: CDWCH_CHARGE_TYPE_PREPAID,
}
