package tencentcloud

const (
	DNS_FORWARD_STATUS_ENABLE   = "ENABLED"
	DNS_FORWARD_STATUS_DISABLED = "DISABLED"
)

var PRIVATE_DNS_FORWARD_STATUS = []string{
	DNS_FORWARD_STATUS_ENABLE,
	DNS_FORWARD_STATUS_DISABLED,
}
