package tencentcloud

const (
	TCAPLUS_IDL_TYPE_PROTO = "PROTO"
	TCAPLUS_IDL_TYPE_TDR   = "TDR"
	TCAPLUS_IDL_TYPE_MIX   = "MIX"
)

var TCAPLUS_IDL_TYPES = []string{
	TCAPLUS_IDL_TYPE_PROTO,
	TCAPLUS_IDL_TYPE_TDR,
}

const (
	TCAPLUS_FILE_EXT_TYPE_PROTO = "proto"
	TCAPLUS_FILE_EXT_TYPE_XML   = "xml"
)

var TCAPLUS_FILE_EXT_TYPES = []string{
	TCAPLUS_FILE_EXT_TYPE_PROTO,
	TCAPLUS_FILE_EXT_TYPE_XML,
}

var FileExtTypeMatch = map[string]map[string]bool{
	TCAPLUS_IDL_TYPE_PROTO: {
		TCAPLUS_FILE_EXT_TYPE_PROTO: true,
	},
	TCAPLUS_IDL_TYPE_TDR: {
		TCAPLUS_FILE_EXT_TYPE_XML: true,
	},
	TCAPLUS_IDL_TYPE_MIX: {
		TCAPLUS_FILE_EXT_TYPE_PROTO: true,
		TCAPLUS_FILE_EXT_TYPE_XML:   true,
	},
}

const (
	TCAPLUS_TABLE_IDL_TYPE_PROTO = "PROTO"
	TCAPLUS_TABLE_IDL_TYPE_TDR   = "TDR"
)

var TCAPLUS_TABLE_IDL_TYPES = []string{
	TCAPLUS_TABLE_IDL_TYPE_PROTO,
	TCAPLUS_TABLE_IDL_TYPE_TDR,
}

const (
	TCAPLUS_TABLE_TYPE_GENERIC = "GENERIC"
	TCAPLUS_TABLE_TYPE__LIST   = "LIST"
)

var TCAPLUS_TABLE_TYPES = []string{
	TCAPLUS_TABLE_TYPE_GENERIC,
	TCAPLUS_TABLE_TYPE__LIST,
}
