package tencentcloud

// all gaap proxy status https://cloud.tencent.com/document/api/608/37023#ProxyInfo
const (
	GAAP_PROXY_CREATING   = "CREATING"
	GAAP_PROXY_RUNNING    = "RUNNING"
	GAAP_PROXY_DESTROYING = "DESTROYING"
	GAAP_PROXY_OPENING    = "OPENING"
	GAAP_PROXY_CLOSING    = "CLOSING"
	GAAP_PROXY_CLOSED     = "CLOSED"
	GAAP_PROXY_ADJUSTING  = "ADJUSTING"
	GAAP_PROXY_ISOLATING  = "ISOLATING"
	GAAP_PROXY_ISOLATED   = "ISOLATED"
	GAAP_PROXY_UNKNOWN    = "UNKNOWN"
)
