package tencentcloud

const (
	DNSPOD_DOMAIN_MARK_YES = "yes"
	DNSPOD_DOMAIN_MARK_NO  = "no"
)

var DNSPOD_DOMAIN_MARK_TYPE = []string{
	DNSPOD_DOMAIN_MARK_YES,
	DNSPOD_DOMAIN_MARK_NO,
}

const (
	DNSPOD_DOMAIN_STATUS_ENABLE  = "enable"
	DNSPOD_DOMAIN_STATUS_DISABLE = "disable"
)

var DNSPOD_DOMAIN_STATUS_TYPE = []string{
	DNSPOD_DOMAIN_STATUS_ENABLE,
	DNSPOD_DOMAIN_STATUS_DISABLE,
}
