package tencentcloud

const (
	CSS_DOMAIN_TYPE_PUSH      = 0
	CSS_DOMAIN_TYPE_PLAY_BACK = 1

	CSS_DOMAIN_STATUS_DEACTIVATED = 0
	CSS_DOMAIN_STATUS_ACTIVATED   = 1

	CSS_PLAY_TYPE_MAINLAND         = 0
	CSS_PLAY_TYPE_GLOBAL           = 1
	CSS_PLAY_TYPE_OUTSIDE_MAINLAND = 2

	CSS_DELAY_LIVE_LVB = 0
	CSS_DELAY_LIVE_LCB = 1

	CSS_OWERSHIP_VIRIFIED = 0

	CSS_VERIFY_TYPE_DB_CHECK   = "dbCheck"
	CSS_VERIFY_TYPE_DNS_CHECK  = "dnsCheck"
	CSS_VERIFY_TYPE_FILE_CHECK = "fileCheck"
)
