package tencentcloud

const (
	MONGODB_INSTANCE_STATUS_INITIAL    = 0
	MONGODB_INSTANCE_STATUS_PROCESSING = 1
	MONGODB_INSTANCE_STATUS_RUNNING    = 2

	MONGODB_ENGINE_VERSION_3_WT    = "MONGO_3_WT"
	MONGODB_ENGINE_VERSION_36_WT   = "MONGO_36_WT"
	MONGODB_ENGINE_VERSION_3_ROCKS = "MONGO_3_ROCKS"

	MONGODB_MACHINE_TYPE_GIO    = "GIO"
	MONGODB_MACHINE_TYPE_TGIO   = "TGIO"
	MONGODB_MACHINE_TYPE_HIO    = "HIO"
	MONGODB_MACHINE_TYPE_HIO10G = "HIO10G"

	MONGODB_CLUSTER_TYPE_REPLSET = "REPLSET"
	MONGODB_CLUSTER_TYPE_SHARD   = "SHARD"
)

var MONGODB_ENGINE_VERSION = []string{
	MONGODB_ENGINE_VERSION_3_WT,
	MONGODB_ENGINE_VERSION_36_WT,
	MONGODB_ENGINE_VERSION_3_ROCKS,
}

var MONGODB_MACHINE_TYPE = []string{
	MONGODB_MACHINE_TYPE_GIO,
	MONGODB_MACHINE_TYPE_TGIO,
}

var MONGODB_CLUSTER_TYPE = []string{
	MONGODB_CLUSTER_TYPE_REPLSET,
	MONGODB_CLUSTER_TYPE_SHARD,
}
