package tencentcloud

const (
	CDH_CHARGE_TYPE_PREPAID = "PREPAID"

	CDH_PREPAID_RENEW_FLAG_NOTIFY_AND_AUTO_RENEW           = "NOTIFY_AND_AUTO_RENEW"
	CDH_PREPAID_RENEW_FLAG_NOTIFY_AND_MANUAL_RENEW         = "NOTIFY_AND_MANUAL_RENEW"
	CDH_PREPAID_RENEW_FLAG_DISABLE_NOTIFY_AND_MANUAL_RENEW = "DISABLE_NOTIFY_AND_MANUAL_RENEW"

	CDH_HOST_STATE_PENDING        = "PENDING"
	CDH_HOST_STATE_LAUNCH_FAILURE = "LAUNCH_FAILURE"
	CDH_HOST_RUNNING              = "RUNNING"
	CDH_HOST_EXPIRED              = "EXPIRED"

	CDH_ZONE_SOLD_OUT_FOR_SPECIFIED_INSTANCE_ERROR = "ResourceInsufficient.ZoneSoldOutForSpecifiedInstance"
)

var CDH_PREPAID_PERIOD = []int{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 24, 36}

var CDH_PREPAID_RENEW_FLAG = []string{
	CDH_PREPAID_RENEW_FLAG_NOTIFY_AND_AUTO_RENEW,
	CDH_PREPAID_RENEW_FLAG_NOTIFY_AND_MANUAL_RENEW,
	CDH_PREPAID_RENEW_FLAG_DISABLE_NOTIFY_AND_MANUAL_RENEW,
}
