package tencentcloud

const (
	CBS_STORAGE_TYPE_CLOUD_BASIC   = "CLOUD_BASIC"
	CBS_STORAGE_TYPE_CLOUD_PREMIUM = "CLOUD_PREMIUM"
	CBS_STORAGE_TYPE_CLOUD_SSD     = "CLOUD_SSD"

	CBS_STORAGE_USAGE_SYSTEM_DISK = "SYSTEM_DISK"
	CBS_STORAGE_USAGE_DATA_DISK   = "DATA_DISK"

	CBS_STORAGE_STATUS_UNATTACHED  = "UNATTACHED"
	CBS_STORAGE_STATUS_ATTACHING   = "ATTACHING"
	CBS_STORAGE_STATUS_ATTACHED    = "ATTACHED"
	CBS_STORAGE_STATUS_EXPANDING   = "EXPANDING"
	CBS_STORAGE_STATUS_ROLLBACKING = "ROLLBACKING"

	CBS_SNAPSHOT_STATUS_NORMAL   = "NORMAL"
	CBS_SNAPSHOT_STATUS_CREATING = "CREATING"
)

var CBS_STORAGE_TYPE = []string{
	CBS_STORAGE_TYPE_CLOUD_BASIC,
	CBS_STORAGE_TYPE_CLOUD_PREMIUM,
	CBS_STORAGE_TYPE_CLOUD_SSD,
}

var CBS_STORAGE_USAGE = []string{
	CBS_STORAGE_USAGE_SYSTEM_DISK,
	CBS_STORAGE_USAGE_DATA_DISK,
}
