package tencentcloud

const (
	DESC_BY_JOB_CONFIG_CREATETIME_0 = 0
	DESC_BY_JOB_CONFIG_CREATETIME_1 = 1
)

var DESC_BY_JOB_CONFIG_CREATETIME = []int{
	DESC_BY_JOB_CONFIG_CREATETIME_0,
	DESC_BY_JOB_CONFIG_CREATETIME_1,
}

const (
	WORK_SPACES_ORDER_TYPE_0 = 0
	WORK_SPACES_ORDER_TYPE_1 = 1
	WORK_SPACES_ORDER_TYPE_2 = 2
	WORK_SPACES_ORDER_TYPE_3 = 3
	WORK_SPACES_ORDER_TYPE_4 = 4
)

var WORK_SPACES_ORDER_TYPE = []int{
	WORK_SPACES_ORDER_TYPE_0,
	WORK_SPACES_ORDER_TYPE_1,
	WORK_SPACES_ORDER_TYPE_2,
	WORK_SPACES_ORDER_TYPE_3,
	WORK_SPACES_ORDER_TYPE_4,
}
