package tencentcloud

const (
	KMS_ORIGIN_TENCENT_KMS = "TENCENT_KMS"
	KMS_ORIGIN_EXTERNAL    = "EXTERNAL"
	KMS_ORIGIN_ALL         = "ALL"
)

var KMS_ORIGIN_FILTER = []string{
	KMS_ORIGIN_TENCENT_KMS,
	KMS_ORIGIN_EXTERNAL,
	KMS_ORIGIN_ALL,
}

var KMS_ORIGIN = []string{
	KMS_ORIGIN_TENCENT_KMS,
	KMS_ORIGIN_EXTERNAL,
}

var KMS_ORIGIN_TYPE = map[string]uint64{
	KMS_ORIGIN_TENCENT_KMS: 1,
	KMS_ORIGIN_EXTERNAL:    2,
}

const (
	KMS_KEY_USAGE_ALL                             = "ALL"
	KMS_KEY_USAGE_ENCRYPT_DECRYPT                 = "ENCRYPT_DECRYPT"
	KMS_KEY_USAGE_ASYMMETRIC_DECRYPT_RSA_2048     = "ASYMMETRIC_DECRYPT_RSA_2048"
	KMS_KEY_USAGE_ASYMMETRIC_DECRYPT_SM2          = "ASYMMETRIC_DECRYPT_SM2"
	KMS_KEY_USAGE_ASYMMETRIC_SIGN_VERIFY_SM2      = "ASYMMETRIC_SIGN_VERIFY_SM2"
	KMS_KEY_USAGE_ASYMMETRIC_SIGN_VERIFY_RSA_2048 = "ASYMMETRIC_SIGN_VERIFY_RSA_2048"
	KMS_KEY_USAGE_ASYMMETRIC_SIGN_VERIFY_ECC      = "ASYMMETRIC_SIGN_VERIFY_ECC"
)

var KMS_KEY_USAGE_FILTER = []string{
	KMS_KEY_USAGE_ALL,
	KMS_KEY_USAGE_ENCRYPT_DECRYPT,
	KMS_KEY_USAGE_ASYMMETRIC_DECRYPT_RSA_2048,
	KMS_KEY_USAGE_ASYMMETRIC_DECRYPT_SM2,
	KMS_KEY_USAGE_ASYMMETRIC_SIGN_VERIFY_SM2,
	KMS_KEY_USAGE_ASYMMETRIC_SIGN_VERIFY_RSA_2048,
	KMS_KEY_USAGE_ASYMMETRIC_SIGN_VERIFY_ECC,
}

var KMS_KEY_USAGE = []string{
	KMS_KEY_USAGE_ENCRYPT_DECRYPT,
	KMS_KEY_USAGE_ASYMMETRIC_DECRYPT_RSA_2048,
	KMS_KEY_USAGE_ASYMMETRIC_DECRYPT_SM2,
	KMS_KEY_USAGE_ASYMMETRIC_SIGN_VERIFY_SM2,
	KMS_KEY_USAGE_ASYMMETRIC_SIGN_VERIFY_RSA_2048,
	KMS_KEY_USAGE_ASYMMETRIC_SIGN_VERIFY_ECC,
}

const (
	KMS_PAGE_LIMIT = 200
)

const (
	KMS_WRAPPING_ALGORITHM_RSAES_PKCS1_V1_5   = "RSAES_PKCS1_V1_5"
	KMS_WRAPPING_ALGORITHM_RSAES_OAEP_SHA_1   = "RSAES_OAEP_SHA_1"
	KMS_WRAPPING_ALGORITHM_RSAES_OAEP_SHA_256 = "RSAES_OAEP_SHA_256"
)

var KMS_WRAPPING_ALGORITHM = []string{
	KMS_WRAPPING_ALGORITHM_RSAES_PKCS1_V1_5,
	KMS_WRAPPING_ALGORITHM_RSAES_OAEP_SHA_1,
	KMS_WRAPPING_ALGORITHM_RSAES_OAEP_SHA_256,
}

const (
	KMS_WRAPPING_KEY_SPEC_RSA_2048 = "RSA_2048"
)

var KMS_WRAPPING_KEY_SPEC = []string{
	KMS_WRAPPING_KEY_SPEC_RSA_2048,
}

const (
	KMS_KEY_STATE_ALL           = "All"
	KMS_KEY_STATE_ENABLED       = "Enabled"
	KMS_KEY_STATE_DISABLED      = "Disabled"
	KMS_KEY_STATE_PENDINGDELETE = "PendingDelete"
	KMS_KEY_STATE_PENDINGIMPORT = "PendingImport"
	KMS_KEY_STATE_ARCHIVED      = "Archived"
)

var KMS_KEY_STATE_FILTER = []string{
	KMS_KEY_STATE_ALL,
	KMS_KEY_STATE_ENABLED,
	KMS_KEY_STATE_DISABLED,
	KMS_KEY_STATE_PENDINGDELETE,
	KMS_KEY_STATE_PENDINGIMPORT,
	KMS_KEY_STATE_ARCHIVED,
}

var KMS_KEY_STATE = []string{
	KMS_KEY_STATE_ENABLED,
	KMS_KEY_STATE_DISABLED,
	KMS_KEY_STATE_PENDINGDELETE,
	KMS_KEY_STATE_PENDINGIMPORT,
	KMS_KEY_STATE_ARCHIVED,
}

var KMS_KEY_STATE_MAP = map[string]uint64{
	KMS_KEY_STATE_ALL:           0,
	KMS_KEY_STATE_ENABLED:       1,
	KMS_KEY_STATE_DISABLED:      2,
	KMS_KEY_STATE_PENDINGDELETE: 3,
	KMS_KEY_STATE_PENDINGIMPORT: 4,
	KMS_KEY_STATE_ARCHIVED:      5,
}
