package tencentcloud

const (
	CUSTOM_RULE_ACTION_TYPE_1 = "1"
	CUSTOM_RULE_ACTION_TYPE_2 = "2"
	CUSTOM_RULE_ACTION_TYPE_3 = "3"
	CUSTOM_RULE_ACTION_TYPE_4 = "4"
)

var CUSTOM_RULE_ACTION_TYPE = []string{
	CUSTOM_RULE_ACTION_TYPE_1,
	CUSTOM_RULE_ACTION_TYPE_2,
	CUSTOM_RULE_ACTION_TYPE_3,
	CUSTOM_RULE_ACTION_TYPE_4,
}

const (
	CUSTOM_RULE_STATUS_0     = "0"
	CUSTOM_RULE_STATUS_1     = "1"
	CUSTOM_RULE_STATUS_0_INT = 0
	CUSTOM_RULE_STATUS_1_INT = 1
)

var CUSTOM_RULE_STATUS = []string{
	CUSTOM_RULE_STATUS_0,
	CUSTOM_RULE_STATUS_1,
}

const (
	CUSTOM_WHITE_RULE_STATUS_0     = "0"
	CUSTOM_WHITE_RULE_STATUS_1     = "1"
	CUSTOM_WHITE_RULE_STATUS_0_INT = 0
	CUSTOM_WHITE_RULE_STATUS_1_INT = 1
)

var CUSTOM_WHITE_RULE_STATUS = []string{
	CUSTOM_WHITE_RULE_STATUS_0,
	CUSTOM_WHITE_RULE_STATUS_1,
}

const (
	CLB_DOMAIN_STATUS_0 = 0
	CLB_DOMAIN_STATUS_1 = 1
)

var CLB_DOMAIN_STATUS = []int{
	CLB_DOMAIN_STATUS_0,
	CLB_DOMAIN_STATUS_1,
}

const (
	CLB_DOMAIN_ENGINE_10 = 10
	CLB_DOMAIN_ENGINE_11 = 11
	CLB_DOMAIN_ENGINE_12 = 12
	CLB_DOMAIN_ENGINE_20 = 20
	CLB_DOMAIN_ENGINE_21 = 21
	CLB_DOMAIN_ENGINE_22 = 22
)

var CLB_DOMAIN_ENGINE = []int{
	CLB_DOMAIN_ENGINE_10,
	CLB_DOMAIN_ENGINE_11,
	CLB_DOMAIN_ENGINE_12,
	CLB_DOMAIN_ENGINE_20,
	CLB_DOMAIN_ENGINE_21,
	CLB_DOMAIN_ENGINE_22,
}

const (
	ISCDN_0 = 0
	ISCDN_1 = 1
	ISCDN_2 = 2
	ISCDN_3 = 3
)

var ISCDN_STSTUS = []int{
	ISCDN_0,
	ISCDN_1,
	ISCDN_2,
	ISCDN_3,
}

const (
	FLOW_MODE_0 = 0
	FLOW_MODE_1 = 1
)

var FLOW_MODE_STATUS = []int{
	FLOW_MODE_0,
	FLOW_MODE_1,
}

const (
	CLS_STATUS_0 = 0
	CLS_STATUS_1 = 1
)

var CLS_STATUS = []int{
	CLS_STATUS_0,
	CLS_STATUS_1,
}

const (
	BOT_STATUS_0 = 0
	BOT_STATUS_1 = 1
)

var BOT_STATUS = []int{
	BOT_STATUS_0,
	BOT_STATUS_1,
}

const (
	API_SAFE_STATUS_0 = 0
	API_SAFE_STATUS_1 = 1
)

var API_SAFE_STATUS = []int{
	API_SAFE_STATUS_0,
	API_SAFE_STATUS_1,
}

const (
	ALB_TYPE_CLB = "clb"
)

var ALB_TYPES = []string{
	ALB_TYPE_CLB,
}

const (
	DescribeHostLimitSuccess = "Success"
)
