package tencentcloud

const (
	TKE_CLUSTER_OS_CENTOS72 = "centos7.2x86_64"
	TKE_CLUSTER_OS_UBUNTU   = "ubuntu16.04.1 LTSx86_64"
)

var TKE_CLUSTER_OS = []string{TKE_CLUSTER_OS_CENTOS72, TKE_CLUSTER_OS_UBUNTU}

const (
	TKE_DEPLOY_TYPE_MANAGED     = "MANAGED_CLUSTER"
	TKE_DEPLOY_TYPE_INDEPENDENT = "INDEPENDENT_CLUSTER"
)

var TKE_DEPLOY_TYPES = []string{TKE_DEPLOY_TYPE_MANAGED, TKE_DEPLOY_TYPE_INDEPENDENT}

const (
	TKE_RUNTIME_DOCKER     = "docker"
	TKE_RUNTIME_CONTAINERD = "containerd"
)

var TKE_RUNTIMES = []string{TKE_RUNTIME_DOCKER, TKE_RUNTIME_CONTAINERD}

const (
	TKE_ROLE_MASTER_ETCD = "MASTER_ETCD"
	TKE_ROLE_WORKER      = "WORKER"
)
