package tencentcloud

const (
	DC_NETWORK_TYPE_VPC   = "VPC"
	DC_NETWORK_TYPE_BMVPC = "BMVPC"
	DC_NETWORK_TYPE_CCN   = "CCN"
)

var DC_NETWORK_TYPES = []string{DC_NETWORK_TYPE_VPC, DC_NETWORK_TYPE_BMVPC, DC_NETWORK_TYPE_CCN}

const (
	DC_ROUTE_TYPE_BGP    = "BGP"
	DC_ROUTE_TYPE_STATIC = "STATIC"
)

var DC_ROUTE_TYPES = []string{DC_ROUTE_TYPE_BGP, DC_ROUTE_TYPE_STATIC}
