// Code generated by iacg; DO NOT EDIT.
package tke

import (
	"context"
	"log"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	tke "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tke/v20180525"

	tccommon "github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/common"
	"github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/internal/helper"
)

func ResourceTencentCloudKubernetesEncryptionProtection() *schema.Resource {
	return &schema.Resource{
		Create: resourceTencentCloudKubernetesEncryptionProtectionCreate,
		Read:   resourceTencentCloudKubernetesEncryptionProtectionRead,
		Delete: resourceTencentCloudKubernetesEncryptionProtectionDelete,
		Schema: map[string]*schema.Schema{
			"cluster_id": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: "cluster id.",
			},

			"kms_configuration": {
				Type:        schema.TypeList,
				Required:    true,
				ForceNew:    true,
				MaxItems:    1,
				Description: "kms encryption configuration.",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"key_id": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "kms id.",
						},
						"kms_region": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "kms region.",
						},
					},
				},
			},

			"status": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "kms encryption status.",
			},
		},
	}
}

func resourceTencentCloudKubernetesEncryptionProtectionCreate(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_kubernetes_encryption_protection.create")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)

	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	var (
		clusterId string
	)
	var (
		request  = tke.NewEnableEncryptionProtectionRequest()
		response = tke.NewEnableEncryptionProtectionResponse()
	)

	if v, ok := d.GetOk("cluster_id"); ok {
		clusterId = v.(string)
	}

	if v, ok := d.GetOk("cluster_id"); ok {
		request.ClusterId = helper.String(v.(string))
	}

	if kMSConfigurationMap, ok := helper.InterfacesHeadMap(d, "kms_configuration"); ok {
		kMSConfiguration := tke.KMSConfiguration{}
		if v, ok := kMSConfigurationMap["key_id"]; ok {
			kMSConfiguration.KeyId = helper.String(v.(string))
		}
		if v, ok := kMSConfigurationMap["kms_region"]; ok {
			kMSConfiguration.KmsRegion = helper.String(v.(string))
		}
		request.KMSConfiguration = &kMSConfiguration
	}

	err := resource.Retry(tccommon.WriteRetryTimeout, func() *resource.RetryError {
		result, e := meta.(tccommon.ProviderMeta).GetAPIV3Conn().UseTkeClient().EnableEncryptionProtectionWithContext(ctx, request)
		if e != nil {
			return tccommon.RetryError(e)
		} else {
			log.Printf("[DEBUG]%s api[%s] success, request body [%s], response body [%s]\n", logId, request.GetAction(), request.ToJsonString(), result.ToJsonString())
		}
		response = result
		return nil
	})
	if err != nil {
		log.Printf("[CRITAL]%s create kubernetes encryption protection failed, reason:%+v", logId, err)
		return err
	}

	_ = response

	if err := resourceTencentCloudKubernetesEncryptionProtectionCreatePostHandleResponse0(ctx, response); err != nil {
		return err
	}

	d.SetId(clusterId)

	return resourceTencentCloudKubernetesEncryptionProtectionRead(d, meta)
}

func resourceTencentCloudKubernetesEncryptionProtectionRead(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_kubernetes_encryption_protection.read")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)

	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	service := TkeService{client: meta.(tccommon.ProviderMeta).GetAPIV3Conn()}

	clusterId := d.Id()

	_ = d.Set("cluster_id", clusterId)

	respData, err := service.DescribeKubernetesEncryptionProtectionById(ctx, clusterId)
	if err != nil {
		return err
	}

	if respData == nil {
		d.SetId("")
		log.Printf("[WARN]%s resource `kubernetes_encryption_protection` [%s] not found, please check if it has been deleted.\n", logId, d.Id())
		return nil
	}
	if respData.Status != nil {
		_ = d.Set("status", respData.Status)
	}

	return nil
}

func resourceTencentCloudKubernetesEncryptionProtectionDelete(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_kubernetes_encryption_protection.delete")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)
	ctx := tccommon.NewResourceLifeCycleHandleFuncContext(context.Background(), logId, d, meta)

	clusterId := d.Id()

	var (
		request  = tke.NewDisableEncryptionProtectionRequest()
		response = tke.NewDisableEncryptionProtectionResponse()
	)

	request.ClusterId = helper.String(clusterId)

	err := resource.Retry(tccommon.WriteRetryTimeout, func() *resource.RetryError {
		result, e := meta.(tccommon.ProviderMeta).GetAPIV3Conn().UseTkeClient().DisableEncryptionProtectionWithContext(ctx, request)
		if e != nil {
			return tccommon.RetryError(e)
		} else {
			log.Printf("[DEBUG]%s api[%s] success, request body [%s], response body [%s]\n", logId, request.GetAction(), request.ToJsonString(), result.ToJsonString())
		}
		response = result
		return nil
	})
	if err != nil {
		log.Printf("[CRITAL]%s delete kubernetes encryption protection failed, reason:%+v", logId, err)
		return err
	}

	_ = response
	if err := resourceTencentCloudKubernetesEncryptionProtectionDeletePostHandleResponse0(ctx, response); err != nil {
		return err
	}

	return nil
}
