package vod

import (
	"context"
	"fmt"
	"log"
	"strconv"
	"strings"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	tccommon "github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/common"
)

func ResourceTencentCloudVodAigcApiToken() *schema.Resource {
	return &schema.Resource{
		Create: resourceTencentCloudVodAigcApiTokenCreate,
		Read:   resourceTencentCloudVodAigcApiTokenRead,
		Delete: resourceTencentCloudVodAigcApiTokenDelete,
		Importer: &schema.ResourceImporter{
			State: schema.ImportStatePassthrough,
		},
		Schema: map[string]*schema.Schema{
			"sub_app_id": {
				Type:        schema.TypeInt,
				Required:    true,
				ForceNew:    true,
				Description: "The VOD [sub application](https://intl.cloud.tencent.com/document/product/266/14574) ID. Users who activated VOD service after December 25, 2023 must specify the application ID.",
			},
			"api_token": {
				Type:        schema.TypeString,
				Optional:    true,
				Computed:    true,
				ForceNew:    true,
				Sensitive:   true,
				Description: "The AIGC API Token value generated by the cloud side. Sensitive value; stored in state in plain text. Optional during `terraform import` to accept a pre-existing token, but SHOULD NOT be set in regular `.tf` configurations.",
			},
		},
	}
}

// parseVodAigcApiTokenId parses the composite resource id of form
// `{sub_app_id}#{api_token}` into its two parts.
func parseVodAigcApiTokenId(id string) (subAppId uint64, apiToken string, err error) {
	parts := strings.Split(id, tccommon.FILED_SP)
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		err = fmt.Errorf("invalid resource id %q, expected format `sub_app_id%sapi_token`", id, tccommon.FILED_SP)
		return
	}
	subAppId, err = strconv.ParseUint(parts[0], 10, 64)
	if err != nil {
		err = fmt.Errorf("invalid resource id %q: sub_app_id part %q is not a valid uint64: %s", id, parts[0], err.Error())
		return
	}
	apiToken = parts[1]
	return
}

func resourceTencentCloudVodAigcApiTokenCreate(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_vod_aigc_api_token.create")()

	logId := tccommon.GetLogId(tccommon.ContextNil)
	ctx := context.WithValue(context.TODO(), tccommon.LogIdKey, logId)
	service := VodService{client: meta.(tccommon.ProviderMeta).GetAPIV3Conn()}

	subAppId := uint64(d.Get("sub_app_id").(int))

	apiToken, err := service.CreateVodAigcApiToken(ctx, subAppId)
	if err != nil {
		return err
	}
	if apiToken == "" {
		return fmt.Errorf("CreateAigcApiToken returned an empty api_token for sub_app_id [%d]", subAppId)
	}

	d.SetId(fmt.Sprintf("%d%s%s", subAppId, tccommon.FILED_SP, apiToken))
	_ = d.Set("api_token", apiToken)

	// The cloud side has ~30s data-sync delay before the new token becomes visible
	// via DescribeAigcApiTokens. Poll until it shows up to avoid spurious drift on
	// the immediately-following Read.
	err = resource.Retry(tccommon.ReadRetryTimeout, func() *resource.RetryError {
		exists, e := service.DescribeVodAigcApiTokenById(ctx, subAppId, apiToken)
		if e != nil {
			return tccommon.RetryError(e)
		}
		if !exists {
			return resource.RetryableError(fmt.Errorf("newly created AIGC API Token is not yet visible in the list for sub_app_id [%d]; retrying", subAppId))
		}
		return nil
	})
	if err != nil {
		return err
	}

	return resourceTencentCloudVodAigcApiTokenRead(d, meta)
}

func resourceTencentCloudVodAigcApiTokenRead(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_vod_aigc_api_token.read")()
	defer tccommon.InconsistentCheck(d, meta)()

	logId := tccommon.GetLogId(tccommon.ContextNil)
	ctx := context.WithValue(context.TODO(), tccommon.LogIdKey, logId)
	service := VodService{client: meta.(tccommon.ProviderMeta).GetAPIV3Conn()}

	subAppId, apiToken, err := parseVodAigcApiTokenId(d.Id())
	if err != nil {
		return err
	}

	_ = d.Set("sub_app_id", int(subAppId))
	_ = d.Set("api_token", apiToken)

	exists, err := service.DescribeVodAigcApiTokenById(ctx, subAppId, apiToken)
	if err != nil {
		return err
	}
	if !exists {
		d.SetId("")
		log.Printf("[WARN]%s resource `tencentcloud_vod_aigc_api_token` [sub_app_id=%d] not found in cloud, please check if it has been deleted.\n", logId, subAppId)
		return nil
	}

	return nil
}

func resourceTencentCloudVodAigcApiTokenDelete(d *schema.ResourceData, meta interface{}) error {
	defer tccommon.LogElapsed("resource.tencentcloud_vod_aigc_api_token.delete")()

	logId := tccommon.GetLogId(tccommon.ContextNil)
	ctx := context.WithValue(context.TODO(), tccommon.LogIdKey, logId)
	service := VodService{client: meta.(tccommon.ProviderMeta).GetAPIV3Conn()}

	subAppId, apiToken, err := parseVodAigcApiTokenId(d.Id())
	if err != nil {
		return err
	}

	if err := service.DeleteVodAigcApiToken(ctx, subAppId, apiToken); err != nil {
		return err
	}

	// Poll until the token disappears from the list (cloud side has ~30s sync delay).
	err = resource.Retry(tccommon.ReadRetryTimeout, func() *resource.RetryError {
		exists, e := service.DescribeVodAigcApiTokenById(ctx, subAppId, apiToken)
		if e != nil {
			return tccommon.RetryError(e)
		}
		if exists {
			return resource.RetryableError(fmt.Errorf("AIGC API Token still exists for sub_app_id [%d]; waiting for sync", subAppId))
		}
		return nil
	})
	if err != nil {
		return err
	}

	return nil
}
